nuxeo/doc.nuxeo.com-content

- src/nxdoc/tutorials/start-customizing-the-nuxeo-platform.md
Removed trailing `/` (they're not urls but references to pages)
> Version override correction

- src/corg/developer-environment-setup/installing-dart-and-related-tools.md
According to [Dart - Installing Dart on Mac][dart], the new command line for installing Dartium is:
brew install dart --with-dartium
[dart]: https://www.dartlang.org/install/mac
> Update Dart installation command on Mac

- src/nxdoc/nuxeo-add-ons/nuxeo-multi-tenant.md
- src/userdoc/adding-features/nuxeo-multi-tenant.md
While reading the nuxeo-multi-tenant documentation page (https://doc.nuxeo.com/userdoc/nuxeo-multi-tenant/), I noticed a few typos, thus I did this Pull Request.
> Fix typos in nuxeo-multi-tenant

- src/corg/development-tools-and-process/quality-assurance-and-continuous-integration/jenkins-plugins/jenkins-pipeline-usage.md
About JIRA pipeline integration, point to the COMPATIBILITY.md file stating the current status.
> Add a link to JIRA Pipeline compatibility status

- src/nxdoc/nuxeo-server/rest-api/json-marshalling/parameterizing-reusing-marshallers.md
- src/nxdoc/nuxeo-server/upgrading-the-nuxeo-platform/upgrade-from-532-to-540/upgrade-to-54-and-jboss-5.md
Table corrected. This is partly an example too for others that might need similar formatting.
_Note:_ The single backticks need escaping with a `\`
> Table Formatting: Corrected

- src/nxdoc/nuxeo-server/workflow/variables-available-in-the-automation-context.md
- src/nxdoc/nuxeo-server/workflow/workflow-engine-faq.md
- src/nxdoc/nuxeo-server/workflow/workflow-how-to-index/how-to-follow-a-transition-if-user-is-member-of-a-group.md
`originatingUser` returns null in a workflow context, whereas `getActingUser()` works in all contexts.
> Use getActingUser() instead of originatingUser

- src/nxdoc/nuxeo-server/content-repository/versioning.md
Doc says:
- All filters referenced by the policy must match in order to apply the policy.
Explorer says:
- Note that filters for a policy are OR-ed
After checking, the explorer is correct => fix doc explanations
> NXDOC-1279 fix filter explanations

- src/nxdoc/nuxeo-server/installation/installing-the-nuxeo-platform-on-linux.md
The apt package changed gnupg|gnupg2 from Depends to Recommends (since APT 1.4.7; ie since Debian 9).
So, `gnupg` may be missing for using `apt-key` and must be installed before.
https://answers.nuxeo.com/general/q/4348e156f6e04e96ba4eda25ed7ad31b/Problem-with-installing-Nuxeo-on
http://metadata.ftp-master.debian.org/changelogs/main/a/apt/apt_1.4.7_changelog
> apt (1.3~exp1) experimental; urgency=medium
> * move gnupg|gnupg2 from apt Depends to Recommends
> GnuPG is missing since Debian 9 (APT 1.4.7)

- src/corg/developer-environment-setup/installing-dart-and-related-tools.md
nuxeo-api-playground requires Dart 1.23.0, build fails with Dart >1.24
> NXDOC-1292 - install Dart 1.23.x

- src/nxdoc/web-ui/web-ui-overview.md
> NXDOC-1307: Adds Safari as supported browser for WebUI

- src/nxdoc/nuxeo-add-ons/digital-asset-management-dam/alternative-command-parameters-for-prores-codec-users.md
- src/nxdoc/nuxeo-server/installation/installing-and-setting-up-related-software.md
Removing the `libfaac` related information as it won't be used anymore.
The whole "Additional Formats Support for FFmpeg" section seemed to be related with it, so I removed it entirely. Please, let me know if we should keep something from it.
> NXP-22777: Remove libfaac encoder mentions

- src/corg/development-tools-and-process/git-usage.md
`--prune` does not seem always wanted
> remove --prune from the push on merged repositories

- src/nxdoc/web-ui/nuxeo-elements/nuxeo-elements-tutorial.md
Path has to be ended with a slash, otherwise it is not working.
Furthermore, the dom-module id had a wrong whitespace.
> WebUI elements example fixes

- src/nxdoc/nuxeo-add-ons/nuxeo-vision.md
The plug-in accepts the two different authentication means provided by Google (and using the API key is easier: No need to install a file on your server)
> Update Google vision configuration parameters info

- src/nxdoc/nuxeo-server/installation/installing-and-setting-up-related-software.md
Update docker package name on Linux (ubuntu) using on CCExtractor Installation description:
sudo apt install docker.io
> Update docker package name on Linux (ubuntu)

- src/nxdoc/nuxeo-server/additional-services/conversion/how-to-contribute-a-command-line-converter.md
The CommandLineDescriptor requires @enabled to be set to true to be activated within Nuxeo.  When using the example out of the box, the server will fail with 'command not found/enabled. https://github.com/nuxeo/nuxeo/blob/master/nuxeo-core/nuxeo-platform-commandline-executor/src/main/java/org/nuxeo/ecm/platform/commandline/executor/service/CommandLineDescriptor.java
> Add @enabled attribute to command line contribution

- src/userdoc/jsf-ui/browsing-content/preview.md
Changed "Mozzilla" to "Mozilla"
> Fixed spelling of Mozilla

- src/nxdoc/nuxeo-server/workflow/workflow-how-to-index/how-to-set-up-a-tasks-dashboard.md
Property 'nt:targetDocumentId' is deprecated, use 'nt:targetDocumentsIds' instead
> Property 'nt:targetDocumentId' is deprecated

- src/corg/development-tools-and-process/git-usage.md
While it's strongly discouraged to version binaries in Git, it is still very useful of being able to see their content changes in git-diff outputs.
> Improve Git diff output on ZIP files

- src/corg/development-tools-and-process/quality-assurance-and-continuous-integration/jenkins-job-configuration.md
> Add your plugin in the Optionals Addons POM;  
that's wrong, it must be added in the marketplace.ini file, as for packages:  
> Add your package in marketplace.ini;
> Fix plugin CI requirement

- src/nxdoc/nuxeo-server/administration/database-configuration/mongodb.md
Starting in MongoDB 3.2, the WiredTiger storage engine is the default storage engine.
> Starting in MongoDB 3.2 WiredTiger is the default storage engine

- src/nxdoc/nuxeo-server/administration/database-configuration/mongodb.md
- src/nxdoc/nuxeo-server/administration/elasticsearch-setup.md
- src/nxdoc/nuxeo-server/advanced-topics/trust-store-and-key-store-configuration.md
Backport of master without the Redis changes (which have not been backported). Mentions that the changes are for Nuxeo >= 9.10-HF22
> NXP-26072/NXP-26074: TLS/SSL connection

- src/nxdoc/nuxeo-add-ons/installing-a-new-package-on-your-instance.md
After meeting with Bertrand: 
Since we are not really mentioning Studio project packages, no need to make a whole section out of it so I just added a link in the page to the Application Definition page. 
Instead, I separated the JSF UI part, and I will update the Application Definition page by deleting the studio tag section and indicating that the configuration in Studio in automatically available when selecting an add-on in another PR.
> NXDOC-1660 Update Application Definition - Package Installation Master

- src/nxdoc/nuxeo-server/core-server/content-repository/content-repository-tutorials/how-to-override-existing-document-types.md
Split into many commits, to isolate the different steps.
- Updated the info on the existing document types (core and DAM).
- Removed outdated document types: Thread, Post and Forum.
- Added new document types: Collection, Collections, HiddenFolder, Root and Relation.
- Added links to the DAM addon page for Audio, Picture and Video.
- Proposed improvement: cleanup the table by formatting it properly.
Based on the following sources for the document type info update:
- [Core document types](https://github.com/nuxeo/nuxeo/blob/a3ff6b1/nuxeo-core/nuxeo-core/src/main/resources/OSGI-INF/CoreExtensions.xml).
- [Audio document type](https://github.com/nuxeo/nuxeo-platform-audio/blob/e820a51/nuxeo-platform-audio-core/src/main/resources/OSGI-INF/core-types-contrib.xml).
- [Picture document …
> NXDOC-1568: Update page How to Override Existing Document Types

- src/client-apps/nuxeo-drive.md
- src/client-apps/nuxeo-drive/nuxeo-drive-installation-configuration.md
Also:
* Fixed `drive-metadata-view.png` link in "Editing Metadata".
To be merged when Drive 4.1.1 is out. I will ping this PR when OK :)
> NXDRIVE-1611: Add new options related to chunk uploads

- src/studio/nuxeo-studio/working-in-studio/roles-and-permissions-section/add-predefined-users-and-groups.md
According to https://jira.nuxeo.com/browse/ELEMENTS-924 and https://nuxeo.quandora.com/frontend/q/4b6fed5de41240c2b672f2301215a71e/Information-about-the-usage-of-user-group-prefix-in-elements, there's no point about raising bugs in the documentation. They should be tracked in JIRA. Instead, the documentation should explicitly explains the standard behavior.
> NXDOC-1902 - Prefix with Users and Groups

- src/nxdoc/nuxeo-add-ons/amazon-s3-online-storage.md
The property *bucket.prefix* has been changed to *bucket_prefix* in the source code.
> Update the bucket_prefix property name

- src/nxdoc/nuxeo-server/additional-services/conversion.md
The converter contribution now hass a new bypassIfSameMimeType parameter allowing the converter service to bypass the converter if the input and output format is the same and if there is no need for any conversion.
> NXDOC-1918: documenting the new bypassIfSameMimeType parameter 

- src/client-apps/nuxeo-drive/nuxeo-drive-faq.md
Also add a note about GNU/Linux support for non-listed or older distributions.
> NXDRIVE-1819: macOS 10.11 has been dropped

- src/studio/nuxeo-studio/tutorials/eclipse-export.md
- src/studio/nuxeo-studio/tutorials/how-to-enable-package-specific-features-in-studio-for-dam-or-virtual-navigation.md
- src/studio/nuxeo-studio/tutorials/maven-integration.md
- src/studio/nuxeo-studio/tutorials/referencing-an-externally-defined-operation.md
- src/studio/nuxeo-studio/tutorials/referencing-an-externally-defined-type.md
Since the new Studio header page in 3.21.0 will contain a link to Nuxeo Studio tutorials, we need to clean the current How To listing in https://doc.nuxeo.com/studio/tutorials/.
> Normalize Studio How To Page Titles

- src/nxdoc/nuxeo-server/events-and-messages/nuxeo-stream.md
For now only for FT no backport needed.
> NXDOC-2002: streamStatus probe enable by default on health check

- src/nxdoc/nuxeo-server/additional-services/nuxeo-stream.md
The 1010 version is now exactly the same page as in master (including NXDOC-2002) except for the health check/probe which works differently in 10.10.
> NXDOC-1936: Backport retry policy and other update from master

- src/client-apps/nuxeo-drive.md
- src/client-apps/nuxeo-drive/nuxeo-drive-faq.md
- src/client-apps/nuxeo-drive/nuxeo-drive-installation-configuration.md
- The minimum version supported on Debian is 9.0.0.
- The minimum version supported on Fedora is 25.
- The minimum version supported on Ubuntu is 16.04.1.
- I sorted paragraphs to be consistent though the whole documentation and Nuxeo Drive repository: GNU/Linux, then macOS and finally Windows.
> NXDRIVE-1408: Improve GNU/Linux details

- src/nxdoc/nuxeo-add-ons/digital-asset-management-dam/supported-file-formats.md
Remove the delivery notion from the table header. It is misleading, will update the whole doc later with a larger approach.
> Remove delivery notion (misleading)

- src/corg/developer-environment-setup/getting-the-nuxeo-source-code.md
This requires to be checked, I basically replaced 5.6 with 10.10, but exact naming may have changed. For example, there were 5.6.1, 5.6.2, ... but we don't do that anymore since 10.10 (we only have HF)
> Changing examples, using a more recent version

- src/corg/development-tools-and-process/maven-usage.md
Change hotfix-releases single proxy to a group containing proxy to mavenin.nuxeo.com and packages.nuxeo.com
> NCI-44: Change hotfix-releases repo to a group

- src/nxdoc/nuxeo-server/rest-api/rest-api-entity-types.md
Remove inline comments from JSON examples and add the corresponding notes below the panel.
> NXDOC-1278: remove comments from JSON examples

- src/corg/development-tools-and-process/maven-usage.md
Use hotfix-releases-group to access maven releases packages.
It is a proxy repository group redirecting to `hotfix-releases` on mavenin and `maven-hotfix-releases·` on packages.
> NCI-44: nexus hotfix releases group

- src/nxdoc/nuxeo-server/administration/configuration-parameters-index-nuxeoconf.md
It would probably be worth grouping the properties in heading sections to make the TOC more usable.
Where there are multiple default values I would put them into a list starting on a new line.
Also, there are a few references to JBoss, not sure if these are relevant or useful?
> Wide configuration table converted to headings

- src/client-apps/nuxeo-drive.md
This is not true since 2018-10-23 (latest 3.x version). Version 3.x used to be MSI files and thus the documentation was accurate. Newer versions are EXE files.
> [Drive] Remove obsolete use of Microsoft Tools

- src/client-apps/nuxeo-drive.md
The mix between `auto_updates` and `auto_update` was confusing.
I also expanded the local configuration's file example to be more clear.
Related question: https://answers.nuxeo.com/general/q/01628a2282ec4676b3b78a55dabbfc67/Nuxeo-Drive-Creating-config-ini-file
> NXDRIVE-2248: Improve the Features section

- src/nxdoc/nuxeo-server/administration/configuration-parameters-index-nuxeoconf.md
Properties `nuxeo.vcs.fulltext.search.disabled` and `nuxeo.vcs.fulltext.disabled` can be used to DBS as well.
> Clarify full text indexing configuration

- src/nxdoc/nuxeo-server/data-store/data-modeling/schema-fields.md
This can be backported to 10.10 and 9.10.
> NXDOC-2228: use DeltaLong.valueOf and not DeltaLong.deltaOrLong

- src/nxdoc/web-ui/web-ui-functional-testing.md
When copy/pasting the `package.json` file, we have this error 
```shell
npm ERR! code EJSONPARSE
npm ERR! file /Users/dmetzler/src/github.com/dmetzler/nuxeo-sample-ftest/package.json
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token } in JSON at position 181 while parsing near '...t --tags=@watch",
npm ERR! JSON.parse   },
npm ERR! JSON.parse   "license": "Apa...'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dmetzler/.npm/_logs/2020-11-18T13_44_59_713Z-debug.log
```
> Fix malformed JSON

- src/client-apps/nuxeo-drive/nuxeo-drive-faq.md
Even if the required Windows Update (KB) is quite old, we need to document it because Drive won't start on machines without it. It will be used by the support (cc @pabgrall).
> NXDRIVE-2312: Documente the required KB for out-of-date Windows versions

- README.md
I encountered this trying run the documentation locally:
```
[Browsersync] Access URLs:
------------------------------------------------
Local: http://localhost:3000/nxdoc/next
External: http://192.168.1.74:3000/nxdoc/next
------------------------------------------------
UI: http://localhost:3001
UI External: http://localhost:3001
------------------------------------------------
[Browsersync] Serving files from: /Users/mnixo/Repositories/doc.nuxeo.com-content/site
[Browsersync] Watching files...
metalsmith-get-metadata:info Getting Metadata +0ms
doc-builder:info Starting build: /Users/mnixo/Repositories/doc.nuxeo.com-content/src +0ms
resolve-edit-path:error Incorrect push_url or repository matcher: https://github.com/nuxeo/doc.nuxeo.com-content +0ms
docs-server:error Docs build error +0ms …
```
> [Suggestion] Fix installation steps

- src/nxdoc/web-ui/web-ui-tutorials/web-ui-routing.md
The last commit updates all the links to properly reference the code. I chose to go with a [fixed recent commit from `master`](https://github.com/nuxeo/nuxeo-web-ui/commit/72abdc5a3cd2d28d7ead61845cda2cd016105b3b) to avoid eventually miss the referenced lines. Ideally we would point to the commit tagged with the LTS release. Let me know what you think!
> NXDOC-2201: Update Web UI routing documentation

- src/nxdoc/web-ui/nuxeo-elements.md
- src/nxdoc/web-ui/nuxeo-elements/nuxeo-elements-tutorial.md
- src/nxdoc/web-ui/web-ui-overview.md
Checking with @Gabez0r before creating backports for `2021` (v10.x), `1010` (v10.x) and `910` (v6.x).
- This is the only occurrence of node versions I could find in the doc.
- I don't think there's the need to include the npm version since the mapping is [publicly available](https://nodejs.org/en/download/releases/).
- Maybe we should also not include the "last verified versions for this tutorial" as we're now referencing just a major version instead of a maj.min.patch version.
> NXDOC-2226: remove node version in elements tutorial

- src/nxdoc/nuxeo-server/administration/configuration-parameters-index-nuxeoconf.md
We noticed differences between the documentation and the values set on the nuxeo.defaults, this is a simple update.
See: https://github.com/nuxeo/nuxeo/blob/35623ac199ba14e51d2a3d9228b8cd6715ee1881/server/nuxeo-nxr-server/src/main/resources/templates/common-base/nuxeo.defaults#L133
Can be applied in 10.10 and 9.10 version, see https://jira.nuxeo.com/browse/NXP-23761
> Update elasticsearch default configuration

- src/client-apps/nuxeo-drive.md
Documentation for the two new options added in the Nuxeo Drive config file.
The feature will be released in Drive 5.0.0
> NXDRIVE-2442: Add documentation for mutual TLS options

- src/nxdoc/nuxeo-add-ons/nuxeo-for-salesforce.md
LTS 2019 links should not point to LTS 2021 source code.
> Fix bad links, point to matching branch.

- src/nxdoc/nuxeo-server/data-store/persistence-architecture/file-storage.md
The example here has:
`<property name="blob:xpath=files/*/file">attachments</property>`
The correct operator for glob match should be `~`:
`<property name="blob:xpath~files/*/file">attachments</property>`
> Change example operator for NXDOC-2336

- src/nxdoc/web-ui/web-ui-tutorials/how-to-use-rich-text-editor-rte-for-article-publishing.md
We need to document how to customize the document picker for the Web UI's rich text editor.
Make it centered around a real life use case like headless article publishing, potential structure as follows
Using and customizing the rich text editor for article publishing
Use case introduction
What elements can I use?
How to retrieve the content in my external system?
How do I reference images in my article?
How do I keep track of which images are being used in my articles?
> NXDOC-2332 RTE Customization

- src/nxdoc/nuxeo-server/administration/variables-and-configuration/configuration-parameters-index-nuxeoconf.md
- src/nxdoc/web-ui/web-ui-release-notes.md
- src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-0-to-3-0-5.md
- src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-6.md
- src/nxdoc/web-ui/web-ui-upgrade-notes.md
- src/nxdoc/web-ui/web-ui-upgrade-notes/web-ui-lts-2021-upgrade-notes.md
- src/nxdoc/web-ui/web-ui-upgrade-notes/web-ui-upgrade-notes-lts-2021.md
Brings release notes for Web UI from 3.0.0 to 3.0.6 and sets up the hierarchy for future ones
Content can be reviewed but references some pages around the bulk actions documentation that do not exist yet and will be created with NXDOC-2333
> NXDOC-2358 NXDOC-2357 Web UI release notes up to 3.0.6

- src/nxdoc/web-ui/web-ui-release-notes.md
- src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-8.md
- src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-9.md
- src/nxdoc/web-ui/web-ui-tutorials/how-to-create-bulk-edit-form-studio.md
- src/nxdoc/web-ui/web-ui-tutorials/web-ui-bulk-actions.md
To be merged Jan. 7 2022,  release will be available on Jan. 10
> NXDOC-2411: how to configure bulk edit

- src/nxdoc/web-ui/web-ui-release-notes.md
- src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-10.md
- src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-9.md
NXDOC-2428: Release notes for Web UI 3.0.10
@manonlumeau Release GA on Feb. 21, this branch is to be merged on Feb. 18.
> NXDOC-2428: Release notes for Web UI 3.0.10

- src/nxdoc/web-ui/web-ui-tutorials/web-ui-deployment.md
Fix doc to specify that require directive is only needed at the deployment-fragment level (require on contribution .xml no longer valid as of LTS 2021) and use nuxeo-cold-storage for examples.
> NXDOC-2468: Update web-ui-deployment for 2021

- src/nxdoc/web-ui/nuxeo-elements/nuxeo-elements-tutorial.md
Specify version of nuxeo-elements to use when installed via bower in nuxeo-elements-tutorial (should be 2.4.x for LTS 2019 version of tutorial).
> NXDOC-2467: nuxeo-elements-tutorial version update

- src/nxdoc/web-ui/web-ui-release-notes.md
- src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-14.md
- src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-15.md
- src/nxdoc/web-ui/web-ui-tutorials/web-ui-bulk-actions.md
NXDOC-2496: Web UI 3.0.15 release notes
Release will be GA on Monday, Sept. 19
=> To be merged on Sept. 16 or earlier if needed and backported to LTS 2021
> NXDOC-2496: Web UI 3.0.15 release notes

- src/nxdoc/web-ui/web-ui-release-notes.md
- src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-15.md
- src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-16.md
Version already GA.
These release notes can be merged anytime and should be backported to LTS 2021.
> NXDOC-2513: Web UI 3.0.16 release notes

- assets/nxdoc/master/web-ui-accessibility/2023-01-nuxeo-web-ui-3-0-18-vpat.pdf
- assets/nxdoc/master/web-ui-overview/2022-09-nuxeo-web-ui-lts-2021-3-0-15-VPAT.pdf
- src/nxdoc/web-ui/web-ui-accessibility.md
Web UI 3.0.18 is publicly available, this PR can be merged anytime
Needs to be backported to LTS 2021.
> NXDOC-2533: update web ui vpat for 3.0.18

- src/nxdoc/nuxeo-server/administration/configuration-parameters-index-nuxeoconf.md
elasticsearch.restClient.socketTimeoutMs => 121000
> NXDOC-2541: update default value for socketTimeout

- src/nxdoc/web-ui/web-ui-release-notes.md
- src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-20.md
- src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-21.md
The release is generally available on March 27.
This needs to be backported to the LTS 2021 branch.
> NXDOC-2550: Release notes for web ui 3.0.21

- src/nxdoc/nuxeo-server/administration.md
- src/nxdoc/nuxeo-server/administration/how-to-clean-up-content.md
- src/nxdoc/nuxeo-server/administration/maintenance.md
Goal is to cover:
* how content is cleaned up
* what options are available
* what they require
* how / when they should be used 
* to what effect
Options to cover:
* Orphan versions cleanup => https://doc.nuxeo.com/rest-api/1/versions-endpoint/#garbage-collect-orphaned-versions 
* Completed workflows cleanup
* Orphan binaries cleanup => https://doc.nuxeo.com/nxdoc/garbage-collecting-orphaned-blobs/
* Audit log purge => https://doc.nuxeo.com/nxdoc/purging-audit-logs-nxp_logs/ 
Expected outcome:
* Customers understand what options are available to them
* Customers can ask the cloud team to leverage a particular option for their need
* Cloud team is able to understand which options are available and what is best suited for a particular customer
* Customers and cloud team can leverage the …
> NXDOC-2575: how to clean up content

- src/nxdoc/web-ui/web-ui-release-notes.md
- src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-25.md
- src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-26.md
- src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-27.md
~Release GA on Aug. 23~
Release was skipped due to a last minute regression that we could not fix in time. This PR will be updated for 3.0.27 when we are getting closer to  release. Please do not merge in between.
> NXDOC-2586: web ui 3.0.26 release notes

- src/nxdoc/nuxeo-add-ons/amazon-s3-online-storage.md
The CORS config in the S3 bucket has to be written in JSON now, not in XML
> Rewrite CORS config into JSON

- src/nxdoc/nuxeo-server/rest-api/allowed-hosts-configuration.md
A configuration property to setup a host whitelist for HTTP requests.
> task-NXDOC-2676-document-the-nuxeo.allowed.hosts-param

- Dockerfile
Fix errors when trying to build such as:
Command failed: git remote get-url --push origin
fatal: detected dubious ownership in repository at '/node-web-app' To add an exception for this directory, call:
git config --global --add safe.directory /node-web-app
> Fix dubious ownership in repository error

- src/nxdoc/nuxeo-server/platform-services/automation/automation-how-to-index/howto-manage-relations.md
Wrong name for the folder to create ("relations" instead of originaly "Relations") See bellow in the page the nuxeo-docwithrelations-view-layout.html uses "relations" 
i.e. 
<link rel="import" href="../../relations/nuxeo-se-add-relation-dialog.html"> <link rel="import" href="../../relations/nuxeo-se-document-relations.html"> <link rel="import" href="../../relations/nuxeo-se-remove-relation-button.html">
> NXDOC-2734 Update howto-manage-relations.md
