src/nxdoc/nuxeo-server/upgrading-the-nuxeo-platform/upgrade-from-lts-2015-following-fast-tracks.md
Note that I didn't manage to create a link to the "UI Dedicated Package" title of another tab "From 8.2 to 8.3" using `[UI Dedicated Package](#ui-dedicated-package)`, so I just used italic instead: https://github.com/nuxeo/doc.nuxeo.com-platform-spaces/pull/9/commits/0a698ab8e9f452b0ae9c6d4d24661a89b3b0f64e#diff-5d29fc4b2ebfe7c6d4b2313ce3fd466fR485
=> NXP-19790/NXP-20939: Add Distribution Changes in 8.3 to LTS 2016 upgrade doc

src/nxdoc/nuxeo-server/jsf-ui-framework/nuxeo-jsf-ui/jsf-ui-how-to-index/how-to-customize-the-error-pages.md, src/nxdoc/nuxeo-server/jsf-ui-framework/nuxeo-jsf-ui/jsf-ui-how-to-index/how-to-customize-the-login-page.md, src/nxdoc/nuxeo-server/jsf-ui-framework/nuxeo-jsf-ui/jsf-ui-how-to-index/how-to-override-the-login-page.md, src/nxdoc/nuxeo-server/jsf-ui-framework/theme.md, src/nxdoc/nuxeo-server/jsf-ui-framework/theme/theme-how-to-index.md, src/nxdoc/nuxeo-server/jsf-ui-framework/theme/theme-how-to-index/how-to-declare-the-css-and-javascript-resources-used-in-your-templates.md, src/nxdoc/nuxeo-server/jsf-ui-framework/theme/theme-how-to-index/how-to-override-a-default-style.md, src/nxdoc/nuxeo-server/jsf-ui-framework/theme/theme-upgrade-to-lts-2015.md
Reviewed Themes & Login pages.
=> Lise doc days 2016

src/nxdoc/nuxeo-add-ons/nuxeo-media-publishing.md, src/nxdoc/nuxeo-server/additional-services/binary-metadata.md, src/nxdoc/nuxeo-server/jsf-ui-framework/documents-display-configuration.md, src/nxdoc/nuxeo-server/jsf-ui-framework/documents-display-configuration/document-content-views.md, src/nxdoc/nuxeo-server/jsf-ui-framework/documents-display-configuration/document-layouts.md, src/nxdoc/nuxeo-server/jsf-ui-framework/documents-display-configuration/document-views.md
- Review Media Publishing
- Review Binary Metadata
- Review Documents Display Configuration (and sub-pages: document layouts, document views and document content views)
=> LTS2016 doc days Andre

src/nxdoc/desktop-and-mobile/nuxeo-mobile.md
`labels` was duplicated and malformed
=> Frontmatter: Corrected

src/nxdoc/generic-multi-excerpts.md, src/nxdoc/tutorials/quick-start-series/nuxeo-platform-feature-table.md
Ready to be merge for a blog post, can be improved later.
=> Nxdoc 964 update feature table

src/nxdoc/tutorials/start-customizing-the-nuxeo-platform/getting-started-with-nuxeo-generator.md
=> Add LocalDeploy class import

build.js, package.json
Builder Version Upgrade fixes concurrency issue on Mac.
**Don't merge**: Waiting for confirmation from Mac users.
=> Master mac fix

src/admindoc/monitoring-and-maintenance/hotfixes-installation-notes-for-nuxeo-platform-60.md
=> NXDOC-1021 : HF34 install notes

src/nxdoc/nuxeo-add-ons/digital-asset-management-dam/supported-file-formats.md
related to https://jira.nuxeo.com/browse/NXDOC-1001
=> add link to imagemasgick formats

src/nxdoc/marketplace-add-ons/nuxeo-csv.md
=> NXDOC-1073 : W3C date format use in complex types

src/corg/working-on-nuxeo-sources/unit-testing/random-tests.md
Document usage on class and feature class.
Further describe the `RELAX` mode.
Remove occurrences of  `&nbsp;`
=> RandomBug usage on class or feature and RELAX mode

src/studio/index.md
*Merge if everything is correct*
=> Section: Added

src/nxdoc/client-sdks.md, src/nxdoc/desktop-and-mobile.md, src/nxdoc/nuxeo-add-ons.md, src/nxdoc/nuxeo-server.md, src/nxdoc/nuxeo-tools.md, src/nxdoc/tutorials.md, src/nxdoc/web-ui.md, src/userdoc/index.md
*Merge if everything looks correct*
=> Added Sections

package.json, src/nxdoc/nuxeo-server/administration/file-storage-configuration.md
Also added start path for local server start up
=> File-storage-configuration: related content fixed

src/nxdoc/nuxeo-server/jsf-ui-framework/jsf-ui-how-to-index/how-to-override-a-template.md
=> Typo "Space" forgotten

src/nxdoc/nuxeo-server/authentication-and-user-management/using-a-ldap-directory.md
Jboss reference removal : See https://doc.nuxeo.com/nxdoc/compatibility-matrix/
=> Jboss reference removal

src/nxdoc/nuxeo-server/content-repository/persistence-architecture/file-storage.md
Doc for https://jira.nuxeo.com/browse/NXP-21891
=> NXP-21891: dispatch on blob xpath, new glob operator

src/nxdoc/tutorials/start-customizing-the-nuxeo-platform/getting-started-with-nuxeo-cli.md, src/nxdoc/tutorials/start-customizing-the-nuxeo-platform/getting-started-with-nuxeo-studio.md, src/nxdoc/tutorials/transversal-how-tos.md, src/nxdoc/tutorials/transversal-how-tos/how-to-unit-test-studio-bundle.md
Just to let you know; I wasn't able to start `npm run dev` to ensure all my links are ok 👎 
I apologize for that.
=> Improvement NXDOC 1152 add partial deploy page

src/nxdoc/web-ui/nuxeo-elements/nuxeo-elements-tutorial.md
Update Nuxeo elements tutorial
remove gulp references and update requirements
=> Follow NXBT-1515 changes

src/nxdoc/nuxeo-server/monitoring-and-maintenance/hotfixes-installation-notes-for-nuxeo-platform-lts-2016.md
limits before stopping
expiration behavior
=> NXDOC-1059: add info on the license check

src/nxdoc/nuxeo-server/installation/compatibility-matrix.md
Changed the supported Postgres version to 9.6 as per the recommendation of Florent.
=> Changed supported Postgres version to 9.6.

src/nxdoc/nuxeo-server/content-repository/persistence-architecture/file-storage.md
Doc updates for https://jira.nuxeo.com/browse/NXP-22217
=> NXDOC-1200: update BlobManager/BlobProvider doc

src/nxdoc/nuxeo-tools/nuxeo-cli.md
=> Update CLI documentation

src/corg/development-tools-and-process/git-usage.md
Add sample commands browsing the history of two merged repositories
=> Walking Through History After Merge

src/corg/developer-environment-setup.md, src/corg/developer-environment-setup/eclipse-setup.md, src/corg/developer-environment-setup/getting-the-nuxeo-source-code.md, src/corg/developer-environment-setup/installing-dart-and-related-tools.md, src/corg/developer-environment-setup/installing-git.md, src/corg/developer-environment-setup/installing-jdk-and-related-tools.md, src/corg/developer-environment-setup/installing-nodejs-and-related-tools.md, src/corg/developer-environment-setup/intellij-idea-setup.md
Hi, I spent some times to review the CORG documentation. By doing this, I hope that the process for new developers would be a easier. Here's the summary of my modification:
- Edit some expressions
- Make the instructions more « user-friendly »
- Update URLs
- Add the missing installation guide for JDK and Maven
I also plan to include the installation guide with IntelliJ, but let's do it in another PR.
=> CORG Review

src/nxdoc/nuxeo-server/rest-api/rest-api-howtos/howto-develop-with-reactredux.md
Update project name to reactjs-sample-ui
=> Update project name to reactjs-sample-ui

src/nxdoc/client-sdks/using-curl.md
Update the server instance to follow the previous step nightly.nuxeo.com instead of demo.nuxeo.com
=> Update the server instance

src/nxdoc/web-ui/web-ui-roadmap.md
=> Adds Web UI roadmap

src/nxdoc/web-ui/web-ui-roadmap.md
Improves Web Ui roadmap layout
=> Improves Web Ui roadmap layout

src/nxdoc/nuxeo-server/administration/repository-configuration.md
Doc for https://jira.nuxeo.com/browse/NXP-22421
=> NXP-22421: unique child name constraints on PostgreSQL

src/nxdoc/desktop-and-mobile/nuxeo-drive/nuxeo-drive-roadmap.md, src/nxdoc/desktop-and-mobile/nuxeo-mobile/nuxeo-mobile-roadmap.md, src/nxdoc/generic-multi-excerpts.md, src/nxdoc/nuxeo-add-ons/nuxeo-adobe-cc-connector.md, src/nxdoc/nuxeo-server/nuxeo-server-roadmap.md, src/nxdoc/nuxeo-tools/nuxeo-dev-tools-extension.md, src/nxdoc/roadmap.md, src/nxdoc/web-ui/web-ui-roadmap.md
- Added a roadmap page for Nuxeo server 
- Added a roadmap index page
- Added ability to give prodpad feedback from all roadmap pages
=> Roadmap pages

src/nxdoc/desktop-and-mobile/nuxeo-drive/nuxeo-drive-roadmap.md, src/nxdoc/desktop-and-mobile/nuxeo-mobile/nuxeo-mobile-roadmap.md, src/nxdoc/nuxeo-add-ons/nuxeo-adobe-cc-connector.md, src/nxdoc/nuxeo-server/nuxeo-server-roadmap.md, src/nxdoc/nuxeo-tools/nuxeo-cli/nuxeo-cli-roadmap.md, src/nxdoc/roadmap.md, src/nxdoc/web-ui/web-ui-roadmap.md
Just some grammar and layout consistency cleanup.
=> Minor edits

src/nxdoc/nuxeo-server/jsf-ui-framework/layouts-and-widgets-forms-listings-grids/custom-layout-and-widget-templates.md
@atchertchian @ffjdm , could you review also please?
=> NXDOC-921: update lists of lists sample

src/nxdoc/nuxeo-server/administration/configuration-templates.md, src/nxdoc/nuxeo-server/administration/database-configuration.md, src/nxdoc/nuxeo-server/administration/database-configuration/connecting-nuxeo-to-the-database.md, src/nxdoc/nuxeo-server/administration/database-configuration/h2-limitations.md, src/nxdoc/nuxeo-server/administration/database-configuration/mariadb.md, src/nxdoc/nuxeo-server/administration/database-configuration/marklogic.md, src/nxdoc/nuxeo-server/administration/database-configuration/mongodb.md
=> NXDOC-892: Add/update MariaDB config docs

src/nxdoc/nuxeo-add-ons.md
Work in Progress - Do not merge this yet
=> Release 9.2

src/nxdoc/tutorials/getting-started-with-the-nuxeo-platform/setting-up-your-nuxeo-environment.md
! Wait for the 9.2 release to merge it !
=> NXDOC-1258: Update Getting Started with Platform for 9.2

src/nxdoc/nuxeo-add-ons/creating-nuxeo-packages.md
typos, format and wording
TODO: review content of "From a Maven Single Module Project"
=> NXDOC-1127 - late review for PR #226

src/nxdoc/nuxeo-server/content-repository/repository-concepts/schema-fields.md
Commit by @nkerzman that went strange.
=> Updated Boolean definition + linked to Wikipedia

src/nxdoc/nuxeo-server/indexing-and-query/how-to-configure-a-search-filter-with-facets-and-other-aggregates.md, src/nxdoc/tutorials/educational/first-steps-with-studio-technical-documentation-tutorial/custom-content-view-for-documentation-items.md, src/nxdoc/tutorials/educational/first-steps-with-studio-technical-documentation-tutorial/implementing-documentation-items.md, src/nxdoc/tutorials/educational/workflow-use-cases/simple-workflow-example.md, src/nxdoc/tutorials/quick-start-series/from-the-jsf-ui-to-nuxeo-studio.md, src/nxdoc/tutorials/start-customizing-the-nuxeo-platform/getting-started-with-nuxeo-cli.md, src/nxdoc/tutorials/start-customizing-the-nuxeo-platform/getting-started-with-nuxeo-studio.md
To merge when Studio unification release is deployed.
=> NXDOC-1271: Update screenshots for Studio unification

src/nxdoc/web-ui/web-ui-overview.md
Simple change with updated Web UI browser support.
=> NXDOC-1307: Improves Web UI roadmap layout

src/nxdoc/nuxeo-tools/nuxeo-dev-tools-extension.md
Update Nuxeo Browser Extension doc following 1.9.1 release.
=> NXDOC-1323: Update BDE doc

src/nxdoc/nuxeo-server/installation/server-start-and-stop/nuxeoctl-and-control-panel-usage.md
See <https://jira.nuxeo.com/browse/NXP-23122>
=> NXP-23122: Deprecate nuxeoctl register-trial

src/userdoc/web-ui/task.md
=> corrected EN grammar

src/nxdoc/desktop-and-mobile/nuxeo-drive/how-to-configure-nuxeo-drive-globally.md, src/nxdoc/desktop-and-mobile/nuxeo-drive/nuxeo-drive-faq.md
Can be reviewed but **should only be merged after the 8.10-HF17 release** (23/10).
=> NXP-22946: Add How to Configure Nuxeo Drive Globally 810

src/nxdoc/desktop-and-mobile/nuxeo-drive/how-to-configure-nuxeo-drive-globally.md, src/nxdoc/marketplace-add-ons/nuxeo-drive/how-to-configure-nuxeo-drive-globally.md, src/userdoc/adding-features/nuxeo-drive/nuxeo-drive-faq.md
Can be reviewed but **should only be merged after the 7.10-HF33 release** (24/10).
=> NXP-22946: Add How to Configure Nuxeo Drive Globally 710

src/corg/development-tools-and-process/git-usage.md
Add changed files listing and edit in IDE
=> Improve PR checkout sample

assets/studio/2017-11-05-studio-73/app-def.png, assets/studio/2017-11-05-studio-73/studio-modeler-designer.png, assets/studio/2017-11-05-studio-73/web-ui-dependency.png, src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/2017-11-05-studio-73.md
English already reviewed by Lisa.
Merge needed asap please.
=> NXS-4352 Studio 73 release notes

src/nxdoc/nuxeo-server/monitoring-and-maintenance/hotfixes-installation-notes-for-nuxeo-platform-lts-2016.md
NXDOC-1356: Document upgrade_tomcat.ps1 prerequisites and detailed how-to in 8.10
=> NXDOC-1356: Document upgrade_tomcat.ps1 how-to

src/nxdoc/getting-started/best-practices/platform-as-a-service.md
Removed most of the picture with nuxeo.io. I don't have access to the original schema that still reference it and could just be replace by `containers` or something like that.
=> NXDOC-1342 update PAAS doc to remove nuxeo.io

src/nxdoc/nuxeo-server/content-repository/persistence-architecture/file-storage.md
I moved the reference to SQLBinaryManager from the default section to with the other providers.
=> NXDOC-1227: SQLBinaryManager is not part of the default distribution

src/nxdoc/getting-started/best-practices/choosing-how-to-import-data-in-the-nuxeo-platform.md, src/nxdoc/getting-started/develop-with-nuxeo-platform.md, src/nxdoc/getting-started/discover-nuxeo-platform-apis/using-automation.md, src/nxdoc/getting-started/discover-nuxeo-platform-apis/using-workflows.md, src/nxdoc/nuxeo-add-ons/nuxeo-bulk-document-importer.md, src/nxdoc/nuxeo-add-ons/nuxeo-csv.md, src/nxdoc/nuxeo-add-ons/nuxeo-csv/how-to-enable-csv-import-on-a-custom-document-type.md, src/nxdoc/nuxeo-add-ons/nuxeo-live-connect.md, src/nxdoc/nuxeo-server/automation/automation-scripting.md, src/nxdoc/nuxeo-server/indexing-and-query/elasticsearch-hints-cheat-sheet.md, src/nxdoc/nuxeo-server/indexing-and-query/elasticsearch-indexing-logic.md, src/nxdoc/nuxeo-server/indexing-and-query/how-to-make-a-page-provider-or-content-view-query-elasticsearch-index.md, src/nxdoc/nuxeo-server/rest-api/rest-api-endpoints/batch-upload-endpoint.md, src/nxdoc/nuxeo-server/rest-api/rest-api-howtos/howto-upload-file-nuxeo-using-rest-api.md, src/nxdoc/nuxeo-server/runtime-and-component-model/runtime-and-component-model-tutorials/how-to-contribute-to-an-extension.md, src/nxdoc/nuxeo-server/security/file-download-security-policies.md, src/nxdoc/nuxeo-tools/nuxeo-cli.md, src/nxdoc/nuxeo-tools/nuxeo-dev-tools-extension.md, src/nxdoc/web-ui/web-ui-tutorials/how-to-create-and-reuse-custom-element.md, src/nxdoc/web-ui/web-ui-tutorials/web-ui-document-layouts.md, src/nxdoc/web-ui/web-ui-tutorials/web-ui-workflow-tasks.md, src/userdoc/web-ui.md, src/userdoc/web-ui/browse.md
It should be merged on Wednesday 29th of November when the new University platform will be available. Thx!
=> Update NX University links with Docebo URLs

src/nxdoc/nuxeo-server/monitoring-and-maintenance.md, src/nxdoc/nuxeo-server/monitoring-and-maintenance/metrics-and-monitoring.md
Can be reviewed but should not be merged before the 9.3 release.
=> NXDOC-1358: update doc on the status servlet and probes

src/nxdoc/getting-started/best-practices/nuxeo-platform-feature-table.md
EasyShare now in Web UI, replace V.20 with LTS 2018
=> NXDOC-1320: Update for 9.3 release

src/nxdoc/desktop-and-mobile/nuxeo-drive/how-to-configure-nuxeo-drive-globally.md
Can be reviewed but **should only be merged after the 8.10-HF20 release (05/12)**.
=> NXP-23589: Update How to Configure Nuxeo Drive Globally (810)

src/nxdoc/marketplace-add-ons/nuxeo-drive/how-to-configure-nuxeo-drive-globally.md
Can be reviewed but **should only be merged after the 7.10-HF35 release (08/12)**.
=> NXP-23589: Update How to Configure Nuxeo Drive Globally (710)

src/nxdoc/getting-started/best-practices/choosing-how-to-import-data-in-the-nuxeo-platform.md
=> Docdays 2017 Review

src/nxdoc/nuxeo-server/data-lists-and-directories.md, src/nxdoc/nuxeo-server/data-lists-and-directories/directory-and-ui.md, src/nxdoc/nuxeo-server/data-lists-and-directories/how-to-add-a-new-vocabulary.md, src/nxdoc/nuxeo-server/data-lists-and-directories/how-to-translate-a-vocabulary.md
and a note about noSQL implementation
=> NXDOC-1401: typo and wording

assets/nxdoc/how-to-customize-nuxeo-mobile-metadata-layout/ViewDesignerLayout.png, assets/nxdoc/how-to-customize-nuxeo-mobile-themes/ViewDesignerThemes.png, assets/nxdoc/nuxeo-drive/drive_synced_under_root-webui.png, package-lock.json, src/nxdoc/desktop-and-mobile/nuxeo-drive.md, src/nxdoc/desktop-and-mobile/nuxeo-drive/how-to-customize-nuxeo-drive-versioning-policy.md, src/nxdoc/desktop-and-mobile/nuxeo-drive/how-to-customize-the-drive-metadata-edit-layouts.md, src/nxdoc/desktop-and-mobile/nuxeo-drive/how-to-manually-initialize-or-deploy-a-nuxeo-drive-instance.md, src/nxdoc/desktop-and-mobile/nuxeo-drive/nuxeo-drive-faq.md, src/nxdoc/desktop-and-mobile/nuxeo-drive/nuxeo-drive-roadmap.md, src/nxdoc/desktop-and-mobile/nuxeo-drive/nuxeo-drive-update-site.md, src/nxdoc/desktop-and-mobile/nuxeo-drive/nuxeo-drive-user-profile-migration.md, src/nxdoc/desktop-and-mobile/nuxeo-mobile.md, src/nxdoc/desktop-and-mobile/nuxeo-mobile/how-to-customize-nuxeo-mobile-metadata-layout.md, src/nxdoc/desktop-and-mobile/nuxeo-mobile/how-to-customize-nuxeo-mobile-themes.md, src/nxdoc/desktop-and-mobile/nuxeo-mobile/nuxeo-mobile-roadmap.md
=> docdays update for supported IOS devices

src/nxdoc/client-sdks/python-client.md
The content is good, but the formatting still need some improvements. A "simple" conversion from `rst` to `md` is missing.
=> NXDOC-1393: Review Python client

package-lock.json, src/nxdoc/nuxeo-server/administration/internet-information-services-iis.md, src/nxdoc/nuxeo-server/installation.md, src/nxdoc/nuxeo-server/installation/installing-and-setting-up-related-software.md, src/nxdoc/nuxeo-server/installation/installing-the-nuxeo-platform-on-mac-os.md, src/nxdoc/nuxeo-server/installation/installing-the-nuxeo-platform-on-windows.md, src/nxdoc/nuxeo-server/installation/installing-the-nuxeo-platform-on-windows/installing-the-nuxeo-platform-as-a-windows-service.md, src/nxdoc/nuxeo-server/installation/installing-the-nuxeo-platform-on-windows/running-multiple-server-instances-in-windows.md
=> NXDOC 1402: review doc for LTS 2017

src/corg/development-tools-and-process/quality-assurance-and-continuous-integration/jenkins-plugins/jenkins-pipeline-usage.md
=> slack step

src/nxdoc/nuxeo-add-ons/digital-asset-management-dam/how-to-contribute-a-new-video-conversion.md, src/nxdoc/nuxeo-server/advanced-topics/integrating-with-jpa.md, src/nxdoc/nuxeo-server/indexing-and-query/moving-load-from-database-to-elasticsearch.md, src/nxdoc/nuxeo-server/jsf-ui-framework/actions-links-buttons-icons-tabs-and-more/filters-and-access-controls.md, src/nxdoc/nuxeo-server/jsf-ui-framework/jsf-ui-how-to-index/how-to-bubble-errors-from-the-core-layer-in-the-jsf-ui.md, src/nxdoc/nuxeo-server/rest-api/content-enrichers.md, src/nxdoc/nuxeo-server/rest-api/error-handling.md, src/nxdoc/nuxeo-server/upgrading-the-nuxeo-platform/upgrade-from-56-to-58/query-models-and-result-providers-migration-to-content-views-and-page-providers.md
Could be backported to 9.10 too...
=> NXP-23872: deprecate Framework.getLocalService

src/nxdoc/nuxeo-server/rest-api/content-enrichers.md
Reverts nuxeo/doc.nuxeo.com-content#564 this change works only for Nuxeo Platform 10.X and not 9.X
=> Revert "NXP-24089: update to CloseableCoreSession"

src/nxdoc/desktop-and-mobile/nuxeo-drive/how-to-configure-nuxeo-drive-globally.md, src/nxdoc/desktop-and-mobile/nuxeo-drive/how-to-customize-nuxeo-drive-versioning-policy.md, src/nxdoc/desktop-and-mobile/nuxeo-drive/how-to-customize-the-drive-metadata-edit-layouts.md, src/nxdoc/desktop-and-mobile/nuxeo-drive/how-to-manually-initialize-or-deploy-a-nuxeo-drive-instance.md, src/nxdoc/desktop-and-mobile/nuxeo-drive/nuxeo-drive-faq.md, src/nxdoc/desktop-and-mobile/nuxeo-drive/nuxeo-drive-user-profile-migration.md
Can be reviewed but **should only be merged after 9.10 is released**.
=> NXP-23589: Add How to Configure Nuxeo Drive Globally

src/nxdoc/nuxeo-server/monitoring-and-maintenance/hotfixes-installation-notes-for-nuxeo-platform-lts-2016.md
The constraint defined in the document schemas are not validation during the document creation
=> Document the fix on the validation

src/nxdoc/web-ui/web-ui-tutorials/how-to-new-pill.md
It's now available for everybody
=> Remove View Designer availibility

src/nxdoc/getting-started/discover-nuxeo-platform-apis/manipulating-documents.md, src/nxdoc/nuxeo-add-ons/nuxeo-file-system-exporter.md, src/nxdoc/nuxeo-add-ons/nuxeo-for-salesforce.md, src/nxdoc/nuxeo-server/content-repository/persistence-architecture/vcs/examples-of-sql-generated-by-vcs.md, src/nxdoc/nuxeo-server/indexing-and-query.md, src/nxdoc/nuxeo-server/indexing-and-query/indexing-and-querying-how-to-index/how-to-fetch-documents-with-a-query-on-date-parameters.md, src/nxdoc/nuxeo-server/indexing-and-query/nxql.md, src/nxdoc/nuxeo-server/indexing-and-query/page-providers.md, src/nxdoc/nuxeo-server/jsf-ui-framework/content-views.md, src/nxdoc/nuxeo-server/jsf-ui-framework/content-views/content-view-how-to-index/how-to-define-a-new-content-view.md, src/nxdoc/nuxeo-server/jsf-ui-framework/content-views/content-view-how-to-index/how-to-display-non-folderish-documents-files-note-in-the-left-tree.md, src/nxdoc/nuxeo-server/jsf-ui-framework/layouts-and-widgets-forms-listings-grids/standard-widget-types/suggestion-widget-types.md, src/nxdoc/nuxeo-server/rest-api/rest-api-endpoints/query-endpoint.md, src/nxdoc/nuxeo-server/rest-api/rest-api-endpoints/search-endpoints.md, src/nxdoc/nuxeo-server/rest-api/rest-api-howtos/howto-develop-with-angular2.md, src/nxdoc/nuxeo-server/upgrading-the-nuxeo-platform/upgrade-from-56-to-58/query-models-and-result-providers-migration-to-content-views-and-page-providers.md, src/nxdoc/web-ui/web-ui-tutorials/how-to-new-pill.md
Add NXQL ecm:isTrashed
Use ecm:isTrashed instead of ecm:currentLifeCycleState
=> FG: NXDOC-1481 (ecm:isTrashed)

src/nxdoc/nuxeo-add-ons/digital-asset-management-dam/supported-file-formats.md
edits to metadata extraction for Adobe formats
=> Updated supported formats

src/corg/developer-environment-setup/installing-git.md, src/corg/development-tools-and-process/git-usage.md
https://jira.nuxeo.com/browse/NXDOC-1501
=> NXDOC-1501 CORG Git Usage

src/corg/development-tools-and-process/quality-assurance-and-continuous-integration/isolated-testing.md, src/corg/development-tools-and-process/quality-assurance-and-continuous-integration/jenkins-job-configuration.md, src/corg/development-tools-and-process/quality-assurance-and-continuous-integration/jenkins-job-configuration/jenkins-pipeline-usage.md
cleanup https://doc.nuxeo.com/corg/isolated-testing/ ; move job config stuff to https://doc.nuxeo.com/corg/jenkins-job-configuration/
move https://doc.nuxeo.com/corg/jenkins-pipeline-usage/ from https://doc.nuxeo.com/corg/jenkins-plugins/ to https://doc.nuxeo.com/corg/jenkins-job-configuration/ (as a sub page).
https://jira.nuxeo.com/browse/NXBT-2175
=> NXBT-2175: review corg/isolated-testing about pipeline usage

src/corg/development-tools-and-process/git-usage.md
Update the sample using the GitHub privacy ("noreply") email
=> Update Co-authored-by/Reviewed-by sample email

assets/studio/branch-management/branch-management.png, assets/studio/branch-management/create-branch.png, assets/studio/branch-management/create-release.png, assets/studio/maven-integration/maven-gav.png, src/studio/nuxeo-studio/tutorials/how-to-tag-or-release-your-nuxeo-studio-project.md, src/studio/nuxeo-studio/tutorials/maven-integration.md, src/studio/nuxeo-studio/working-in-studio/branch-management.md
This adds the REST API endpoint documentation for releases.
Note that we have to put in in production first :)
=> Studio: Adds REST API endpoint for release

assets/studio/2018-03-05-studio-73-8/field-config-constraint.png, assets/studio/2018-03-05-studio-73-8/field-config-constraint2.png, assets/studio/2018-03-05-studio-73-8/studio-maven-gav-ci.png, assets/studio/2018-03-05-studio-73-8/studio-release-ui.png, src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/2018-03-05-studio-73-8.md
To be deployed on monday march 5.
English review from karin is needed before that.
=> NXDOC-1515 studio 73.8 release notes

src/nxdoc/nuxeo-server/webengine-jax-rs/webengine-tutorials.md
Small update on the links for the jar package and sources. Small wording change.
=> Update webengine tutorial

src/corg/developer-environment-setup/installing-git.md
NXBT-907 is marked as resolved
=> NXBT-907: Remove obsolete warning

assets/studio/application-definition/Screenshot 2014-12-30 11.19.01.png, assets/studio/application-definition/Screenshot 2014-12-30 17.07.00.png, assets/studio/application-definition/addons-list.png, assets/studio/application-definition/application-definition.png, assets/studio/application-definition/application-dependencies.png, assets/studio/application-definition/pending-modifications.png, assets/studio/application-definition/removal-notice.png, assets/studio/application-definition/studio-tag.png, assets/studio/maven-integration/maven-gav.png, assets/studio/releases-and-tags/Screen Shot 2016-03-22 at 00.05.22.png, assets/studio/releases-and-tags/releases-tab.png, assets/studio/releases-and-tags/tags-tab.png, src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/2018-04-02-studio-73-9.md, src/studio/nuxeo-studio/tutorials/how-to-tag-or-release-your-nuxeo-studio-project.md, src/studio/nuxeo-studio/tutorials/maven-integration.md, src/studio/nuxeo-studio/working-in-studio/application-definition.md, src/studio/nuxeo-studio/working-in-studio/releases-and-tags.md
To be merged on April 2 after english review / fixes
=> NXDOC-1537 Studio 73.9 release notes

src/nxdoc/nuxeo-server/monitoring-and-maintenance/hotfixes-installation-notes-for-nuxeo-platform-lts-2017.md
Release notes has been added fro HF01 to HF05
=> Release 592 add installation notes

src/nxdoc/nuxeo-server/monitoring-and-maintenance/hotfixes-installation-notes-for-nuxeo-platform-lts-2016.md
Installation notes for HF28 and the missing previous hotfixes
=> RELEASE-593: add installation notes

src/corg/coding-and-design-guidelines/java-code-style.md
https://nuxeo.slack.com/archives/C031UK21L/p1525798499000095
=> Update Code Templates and Formatter configurations

assets/studio/2018-05-28-studio-73-13/appdef-drive-operations.png, assets/studio/2018-05-28-studio-73-13/appdef-drive.png, assets/studio/2018-05-28-studio-73-13/operations-icon-suggestion.png, assets/studio/2018-05-28-studio-73-13/operations-slot-input-check.png, assets/studio/2018-05-28-studio-73-13/theme-logo-background.png, src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/2018-05-28-studio-73-13.md
Will be deployed on Monday May 28 if tests pass!
=> NXDOC-1591 Studio 73.13 release notes

src/corg/development-tools-and-process/quality-assurance-and-continuous-integration/isolated-testing.md
Copy answer from https://jira.nuxeo.com/browse/NXBT-2318?focusedCommentId=342424&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-342424
Explain how to edit the common template
=> NXBT-2318: how to edit the T&P template

src/corg/working-on-nuxeo-sources/supporting-hot-reload.md
* Updating the hot reload conditions by the **Update Center** interface (only JSF).
=> Updating the hot reload conditions

src/nxdoc/nuxeo-server/installation/server-start-and-stop/nuxeoctl-and-control-panel-usage.md
Added the information about the hotfix version level installed on the platform.
=> Update the mp-list command to be more precise

src/nxdoc/nuxeo-server/administration/setup-best-practices.md
Update log and data setup, the UI configuration is mostly available on JSF.
=> Update log and data setup

src/nxdoc/desktop-and-mobile/nuxeo-drive/nuxeo-drive-installation-configuration.md
Note: You can squash commits when merging, I cannot do it myself as of now.
=> NXP-25167: Update links of Nuxeo Drive installers

assets/studio/token-management/token-management.png, src/studio/nuxeo-online-services-portal/token-management.md, src/studio/nuxeo-studio/nuxeo-studio-designer-git-access.md
Release will be deployed monday July 16.
Doc should be ready as is, maybe needs to be moved somewhere else where it makes more sense?
=> NXDOC-1612 Git access

src/nxdoc/nuxeo-server/installation/server-start-and-stop/nuxeoctl-and-control-panel-usage.md
=> Update the GUI start command (more precise)

src/nxdoc/nuxeo-add-ons/nuxeo-csv/how-to-enable-csv-import-on-a-custom-document-type.md
The Extension Point ID is not configured properly.
=> Ext point ID not configured properly

src/corg/working-on-nuxeo-sources/unit-testing.md
Update the doc so the note are more expressive.
=> Be more explicit

src/nxdoc/getting-started/best-practices/continuous-integration.md
GOAL
- Create a page that explains usual tools and basic methology for CI setup
Notes:
- Not a how to: this is just a high level overview to get people started.
- Customers can easily be scared at the work load it implies: idea is to keep things simple and short, plus we already have good documentation on that topic in the doc.
- Could be improved to advertise how PS can help with this later on.
=> NXDOC-1639 CI best practices

src/nxdoc/nuxeo-server/monitoring-and-maintenance/hotfixes-installation-notes-for-nuxeo-platform-lts-2016.md
indicate on how to resize a column to prevent from potential errors with the audit
=> HF18 update

src/corg/coding-and-design-guidelines/java-code-style.md, src/corg/working-on-nuxeo-sources/unit-testing.md
Fixed formatting issue with `@something.something`
=> NXDOC-1622

src/nxdoc/nuxeo-server/additional-services/nuxeo-stream.md
The link title did not correspond to anything related to that topic.
=> Updates the link title

src/nxdoc/nuxeo-server/core-server/security/security-policy-service.md
Updates due to interface modifications (since 2010)
=> Update the code sample, interfaces have changed.

src/nxdoc/nuxeo-server/authentication-and-user-management/how-to-add-new-fields-to-the-user-profile-or-group-profile.md
* Customise the user UI
* Update the user schema definition
* Update the group schema definition
=> Big update on the user and group schema definition

src/nxdoc/nuxeo-server/authentication-and-user-management/how-to-add-new-fields-to-the-user-profile-or-group-profile.md
* Add an up to date screenshot
* Remove the redondant infos (heading of the callout)
=> Update the doc

src/studio/nuxeo-studio/early-access-program.md, src/studio/nuxeo-studio/jsf-web-ui-migration.md
Possibly delivered around oct 17
=> NXDOC-1650 jsf migration

src/nxdoc/getting-started/best-practices/nuxeo-platform-feature-table.md
=> updates Web UI features

src/studio/nuxeo-studio/working-in-studio/templates.md
https://jira.nuxeo.com/browse/NXDOC-475
NXDOC-475 Add pages in the Templates sections
=> NXDOC-475: Fix Add Templates Doc Page

src/nxdoc/nuxeo-server/authentication-and-user-management/how-to-add-new-fields-to-the-user-profile-or-group-profile.md
* Be more specific in the way we add user schema infos.
=> More infos when defining schemas and directories.

src/nxdoc/getting-started/learning-with-examples/how-to-publish-a-news-feature-in-workspaces.md, src/nxdoc/getting-started/learning-with-examples/how-to-publish-a-news-feature-in-workspaces/add-a-news-content-view-on-workspaces.md, src/nxdoc/getting-started/learning-with-examples/how-to-publish-a-news-feature-in-workspaces/implement-the-news-document.md, src/nxdoc/getting-started/learning-with-examples/how-to-publish-a-news-feature-in-workspaces/implement-the-news-publishing-process.md
NXDOC-1357 Update How to Publish a News Feature in Workspaces with Web UI
https://jira.nuxeo.com/browse/NXDOC-1357
=> NXDOC-1357: Fix JSF UI required on How to Publish a News feature in workspaces

src/nxdoc/nuxeo-add-ons.md, src/nxdoc/nuxeo-add-ons/nuxeo-jsf-to-web-ui.md
NXDOC-1673 Create documentation for JSF to Web UI addon
=> NXDOC-1673: Fix Doc JSF to Web UI add on

src/studio/nuxeo-studio/working-in-studio/vocabularies.md
https://jira.nuxeo.com/browse/NXDOC-1304
=> NXDOC 1304 list default directories

src/studio/nuxeo-studio/working-in-studio/workflow/workflow-screens/graph-tab.md
NXDOC-314 The graph tab of studio doc should be more documented
https://jira.nuxeo.com/browse/NXDOC-314
=> NXDOC-314-graph-tab-doc-update

src/nxdoc/getting-started/learning-with-examples/how-to-publish-a-news-feature-in-workspaces/implement-the-news-document.md
The name of Web UI  items, available with JSF UI add-on,  in automation chains is now Seam for less confusion
=> NXDOC-1357 Fix automation chains webui to seam

src/studio/nuxeo-studio/administering-your-project/naming-conventions.md
Added the transition state naming convention.
=> Transition state naming convention

assets/nxdoc/how-to-insert-user-action/drop-down-menu-validate.png, src/nxdoc/web-ui/web-ui-tutorials/how-to-insert-user-action.md
For fear of merges conflicts, I did not change the screenshot in the page https://doc.nuxeo.com/userdoc/document-actions/
The structure of userdoc is evolving so the updated screenshot will be included later.
=> NXDOC-1718-Update screenshot in tutorial in nxdoc 

assets/nxdoc/web-ui-document-layouts/document_page_1.png, assets/nxdoc/web-ui-document-layouts/document_page_2.png, src/nxdoc/web-ui/web-ui-tutorials/how-to-display-children-documents-listing.md, src/nxdoc/web-ui/web-ui-tutorials/how-to-insert-user-action.md, src/nxdoc/web-ui/web-ui-tutorials/how-to-new-pill.md, src/nxdoc/web-ui/web-ui-tutorials/web-ui-document-layouts.md, src/nxdoc/web-ui/web-ui-tutorials/web-ui-search.md, src/nxdoc/web-ui/web-ui-tutorials/web-ui-workflow-tasks.md
Fix screenshots to new layout, add a call out for quick switcher, check dragndrop usage
=> NXDOC-1745 Update tutorials to use quick switcher and drag n drop 

src/corg/development-tools-and-process/git-usage.md
Update instructions for conversion from Mercurial to Git.
Follow Git commands update.
=> SUPINT-1305 update hg2git

src/studio/nuxeo-studio/nuxeo-studio-designer-git-access.md
Update doc to reflect that tags can be pushed
=> NXDOC-1783

src/nxdoc/nuxeo-tools/nuxeo-cli.md
Whenever we go to higher versions it breaks.
=> Update the doc due to compatibility issues

src/nxdoc/nuxeo-server/administration/database-configuration/postgresql.md
Can be backported in 10.10 as well.
=> NXDOC-1826: reference PostgreSQL TLS/SSL documentation

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-01.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-02.md
To be deployed in prod feb 15 if all goes well!
=> NXDOC-1840

src/nxdoc/nuxeo-server/jsf-ui-framework/jsf-ui-how-to-index/how-to-bubble-errors-from-the-core-layer-in-the-jsf-ui.md
Fix format on related pages for how-to-bubble-errors-from-the-core-layer-in-the-jsf-ui
=> Fix related pages how-to-bubble-errors-from-the-core-layer-in-the-jsf-ui

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-02.md
=> NXDOC-1844

assets/nxdoc/how-to-customize-email-templates/STUDIO-mailTemplateContent.png, assets/nxdoc/how-to-customize-email-templates/STUDIO-mailTemplateCreation.png, assets/nxdoc/how-to-customize-email-templates/studio_mailtemplate_content_2.png, src/nxdoc/nuxeo-server/core-server/content-repository/content-repository-tutorials/how-to-override-existing-document-types.md, src/nxdoc/nuxeo-server/core-server/events-and-listeners/how-to-customize-email-templates.md, src/nxdoc/nuxeo-server/core-server/workflow/workflow-how-to-index/how-to-display-a-buttona-tab-only-when-a-workflow-is-started.md, src/nxdoc/nuxeo-server/installation/registering-your-nuxeo-instance.md, src/nxdoc/nuxeo-server/jsf-ui-framework/jsf-ui-how-to-index/how-to-display-a-button-a-tab-only-when-a-workflow-is-started-jsf.md
Also created: https://jira.nuxeo.com/browse/NXDOC-1855
Link to the spreadsheet: https://docs.google.com/spreadsheets/d/1BDJl6VRZTsK4v8Ddx_MEFEs5K2JvRtyyp-qk8mab-lA/edit?usp=sharing
=> NXDOC-1833 Migrate JSF UI howto

src/nxdoc/web-ui/web-ui-tutorials/web-ui-theme-customization.md
A section has been created under HOWTO: Customize Themes to help users create themes with Studio
=> NXDOC-1816 Studio Theme Override

src/studio/nuxeo-studio/working-in-studio/branding.md
=> Add info on Application Logo

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-02.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-03.md
Can be deployed asap.
I documented changes for 3.7.0 and 3.8.0 (see comments in release notes) so that you can easily update the needed files when NOS team deploys a release to prod while I'm away.
=> NXDOC-1866

src/studio/nuxeo-studio/working-in-studio/application-definition.md
Review Application Definition page following discussion on https://jira.nuxeo.com/browse/NXDOC-1660
=> NXDOC-1660 Update Application Definition - Package Installation Static

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-03.md
Expected date for 3.8.0 deployment in prod: march 20
=> NXDOC-1882 upcoming studio 3.9.0 draft, studio 3.8.0 release

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-03.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-04.md
Should be deployed to prod ~ april 8 to 10
=> NXDOC-1893 studio 3.9.0

src/nxdoc/nuxeo-server/administration/kafka.md
That configuration only make sense for Nuxeo 9.10, LTS-2017.
=> Update no-redis configuration

src/nxdoc/nuxeo-server/administration/kafka.md
That configuration only make sense for Nuxeo 9.10.
=> Update the no-redis cluster

src/nxdoc/nuxeo-server/installation/installing-and-setting-up-related-software.md
brew install ffmpeg does not allow anymore any --with-<option> switches, it returns an error
=> Update ffmpeg install on Mac

src/nxdoc/nuxeo-server/administration/http-and-https-reverse-proxy-configuration.md
Related to nuxeo/nuxeo-tools-docker-priv#24.
=> NXDOC-1900: document how to prevent URL canonicalization on Apache

src/nxdoc/nuxeo-server/core-server/automation/use-of-mvel-in-automation-chains.md
The existing exemple didn't work and throws an error
=> Automation - Update date management when updating properties

src/nxdoc/nuxeo-server/authentication-and-user-management/using-a-ldap-directory.md
provide complete LDAP configuration documentation for nuxeo.conf
=> NXDOC-1905 LDAP configuration options

src/client-apps/nuxeo-drive.md
Users don't find any result by searching for "offline"
=> Update Nuxeo Drive except

src/nxdoc/nuxeo-server/rest-api/rest-api-endpoints/command-endpoint.md
Add an example for the body input parameter.
=> Add input parameter example

src/studio/nuxeo-studio/studio-overview-and-concepts.md, src/studio/nuxeo-studio/tutorials/deploying-your-project-in-dev-mode.md, src/studio/nuxeo-studio/tutorials/eclipse-export.md, src/studio/nuxeo-studio/tutorials/how-to-collaborate-on-a-studio-project.md, src/studio/nuxeo-studio/tutorials/how-to-implement-features-using-branches.md, src/studio/nuxeo-studio/tutorials/how-to-review-nuxeo-studio-configuration.md, src/studio/nuxeo-studio/tutorials/how-to-tag-or-release-your-nuxeo-studio-project.md, src/studio/nuxeo-studio/tutorials/how-to-unit-test-a-studio-bundle.md, src/studio/nuxeo-studio/tutorials/how-to-work-with-git-and-studio-project.md, src/studio/nuxeo-studio/tutorials/how-to-work-with-maintenance-branches.md, src/studio/nuxeo-studio/tutorials/installing-the-studio-jar-manually.md
Former graph is still commented in case we decide to keep it after all. 
I also thought that we could feature the video that is on this page. What do you think?
=> NXDOC-1832 Studio Overview and Concepts

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-04.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-05.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-06.md
Can be merged as soon as review is done
=> NXDOC-1920 release notes for studio 3.10 to 3.12

src/nxdoc/nuxeo-add-ons/nuxeo-for-adobe-cc.md
does not necessarily pertain to new release.  more for readibility of current features.  does not need to wait for upcoming update/release to merge.
=> changes to current doc

src/studio/nuxeo-studio/tutorials/how-to-work-with-git-and-studio-project.md
Remove useless warning on FT 10.2
=> Update How to work with Git Access

src/corg/development-tools-and-process/quality-assurance-and-continuous-integration/jenkins-plugins.md
Add "Convert To Pipeline" Jenkins plugin used in https://jira.nuxeo.com/browse/NXBT-2171
See also https://jira.nuxeo.com/browse/NXBT-2897
=> NXBT-2897: Mention Convert To Pipeline Jenkins plugin

src/nxdoc/nuxeo-add-ons/nuxeo-for-adobe-cc.md
needs screenshots and proofing
=> updates for the june 2019 release

src/client-apps/nuxeo-drive/nuxeo-drive-faq.md
Wating on @vdutat approval to let me know if more information is required.
=> NXDRIVE-1725: Document what local actions are reflected on the server

src/nxdoc/nuxeo-server/data-store/indexing-and-query/nxql.md
=> NXP-26305: add NXQL NOW() doc

src/client-apps/nuxeo-drive/nuxeo-drive-installation-configuration.md
Also replaced "Mio" (french) for "MiB" (english).
=> NXDRIVE-1219: Document the tmp_file_limit option

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md
Deployment scheduled for monday july 22
=> NXDOC-1948: 3.15 deployment and upcoming

src/nxdoc/nuxeo-server/data-store/security/security-policy-service.md
Add some precision to express security policy.
=> Add some precision to express security policy

src/nxdoc/nuxeo-add-ons/amazon-s3-online-storage.md
Waiting for https://github.com/nuxeo/nuxeo/pull/3431 before merge.
Can be backported to 10.10 (after https://github.com/nuxeo/nuxeo/pull/3442)
=> NXP-27805: configurable digest for S3

src/studio/nuxeo-studio/nuxeo-studio-community-cookbook.md
=> SPREAD-380 - Duplicate Studio Cookbook table into Doc

src/studio/nuxeo-studio/nuxeo-studio-community-cookbook.md
https://github.com/nuxeo/nuxeo-studio-community-cookbook/tree/master/modules/nuxeo/inject-html
=> Add Inject HTML Contrib

src/nxdoc/nuxeo-add-ons/template-rendering-addon.md
Update the default behaviour of the Template Rendering Output
=> Add Cookbook Link on Template Rendering

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-09.md
=> NXDOC-1991: release notes for studio 3.20

src/nxdoc/nuxeo-server/data-store/persistence-architecture/file-storage.md
=> NXP-28227 /  NXP-28267 blob dispatch ecm path regexp

src/nxdoc/nuxeo-server/platform-services/workflow/workflow-how-to-index/how-to-refresh-the-task-widget-on-the-summary-tab.md
Fixed typo and added the cancellation operation to the doc page
=> NXDOC-1896: task widget refresh

src/nxdoc/nuxeo-server/events-and-messages/work-and-workmanager.md
=> NXP-28182: Add some note about the GroupJoin

src/nxdoc/nuxeo-server/administration/configuration-parameters-index-nuxeoconf.md, src/nxdoc/nuxeo-server/administration/setup-best-practices.md
=> feature-NXDOC-2018-document_JAVA_OPTS

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-10-11.md
NXDOC-2023: studio 3.21 release
=> NXDOC-2023: studio 3.21 release

src/nxdoc/nuxeo-server/platform-services/automation/automation-scripting.md
=> NXP-28299 : Fix Auth.Logout sample

src/studio/nuxeo-studio/early-access-program.md
remove mention of designer live preview in early access
=> NXDOC-2026: remove mention of designer live preview in early access

src/nxdoc/nuxeo-server/core-server/automation/automation-scripting.md
=> NXP-28299: Fix Auth.Logout sample

src/nxdoc/nuxeo-server/automation/automation-scripting.md
=> NXP-28299: Fix Auth.Logout sample-910

src/studio/nuxeo-online-services-portal/token-management.md, src/studio/nuxeo-studio/working-in-view-designer/nuxeo-studio-designer-git-access.md
Migration to Okta: explain where tokens are needed, why etc
Can be merged anytime (only sentence that's not true yet is that we delegate things to okta until migration happens, not a big deal)
=> NXDOC-2021 Inform about token usage and impacts

src/studio/nuxeo-marketplace/delivering-a-customization-package-through-the-nuxeo-marketplace.md, src/studio/nuxeo-studio/tutorials/how-to-tag-or-release-your-nuxeo-studio-project.md, src/studio/nuxeo-studio/tutorials/how-to-unit-test-a-studio-bundle.md, src/studio/nuxeo-studio/tutorials/maven-integration.md
Related to okta migration
Can be merged anytime
=> NXDOC-2022: tokens, not passwords

assets/userdoc/icons-index/download-document-web-ui-blue.png, src/nxdoc/nuxeo-server/installation.md
- Removed History
- Updated markup to use `dl-boxes` class
=> Download boxes class added

src/studio/nuxeo-online-services-portal/token-management.md
=> NXDOC-2042 warn about mandatory change

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2019-12.md
=> NXDOC-2041: studio 3.23 release notes

src/studio/nuxeo-studio/tutorials/how-to-prepopulate-metadata-creation-document.md
I haven't succeeded to size correctly the table columns, they are not sized properly.
=> NXDOC-2015 - Prepopulate document properties

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2020-01.md
Deployment scheduled for monday January 13, 2020 5AM paris time.
=> NXDOC-2048: release notes studio 3.25

src/nxdoc/web-ui/web-ui-tutorials/how-to-customize-creation-form.md, src/nxdoc/web-ui/web-ui-tutorials/how-to-filter-data-in-directory-suggestion.md
Can be applied to LTS2019, LTS2017.
This is my last doc PR of the year, don't be sad, I'm coming back soon! So I wish to the Doc Team a very happy festive end of year! 2020 will be a huge year with new how-to! Keep it up!
=> NXDOC-2014 - Use Filters in Suggestions

assets/nxdoc/rest-api/new-upload-s3.png, assets/nxdoc/rest-api/new-upload.png, assets/nxdoc/rest-api/resume-upload-s3.png, assets/nxdoc/rest-api/resume-upload.png, src/nxdoc/nuxeo-server/rest-api/rest-api-endpoints/batch-upload-endpoint.md
PlantUML commands are included in comments for history.
To generate all pictures, just type:
```bash
plantuml file.md
```
I already compressed new images using TinyPNG.
=> NXDOC-2040: Add upload sequence diagrams

src/corg/working-on-nuxeo-sources/supporting-hot-reload.md
getLocalService is deprecated. Changed to getService.
=> Java code update

src/studio/nuxeo-online-services-portal/security-improvements-faq.md
=> NXDOC-2063: push back migration deadline

src/nxdoc/nuxeo-server/administration/configuration-parameters-index-nuxeoconf.md, src/nxdoc/nuxeo-server/administration/kafka.md, src/nxdoc/nuxeo-server/administration/monitoring-and-maintenance/reporting-problems.md, src/nxdoc/nuxeo-server/events-and-messages/nuxeo-stream.md
Hi, this needs to be reviewed by support team first, doc team second then I will do a PR for the 10.10 backport, thanks.
=> Feature nxdoc 2064 kafka params

src/studio/nuxeo-online-services-portal/security-improvements-faq.md
Needed urgently (sorry), as migration has been delayed from monday to the week after
=> NXDOC-2074 delay okta migration

src/client-apps/nuxeo-drive/nuxeo-drive-tutorials/how-to-manually-initialize-or-deploy-a-nuxeo-drive-instance.md
Can I have you thoughts @gspradlin? Just to be sure sentences are right enough and if more work is needed to make the whole process easily understanble.
=> NXDRIVE-2050: Add a section for deployment scripts

src/studio/nuxeo-online-services-portal/security-improvements-faq.md, src/studio/nuxeo-online-services-portal/token-management.md, src/studio/nuxeo-studio/working-in-view-designer/nuxeo-studio-designer-git-access.md
=> NXDOC-2079: clarify how to authenticate and use a token

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2020-02-03.md
Deployed to prod monday morning paris time, merge needed quickly sorry :-p
=> NXDOC-2081: studio 3.27 + upcoming changes

src/studio/nuxeo-online-services-portal/security-improvements-faq.md, src/studio/nuxeo-online-services-portal/token-management.md
=> NXDOC-2082: fix typos

src/corg/working-on-nuxeo-sources/functional-testing/selenium-tests.md
=> Code format for clarity

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2020-02-03.md
Already in prod. Not so many changes, no need to rush (I can update the news in studio anyway).
=> NXDOC-2088: studio 3.28

src/studio/nuxeo-online-services-portal/security-improvements-faq.md
Merge needed asap please, used to inform people about how we'll move timeline for MFA go live
=> NXDOC-2089: better inform about timeline

src/studio/nuxeo-online-services-portal/security-improvements-faq.md
Could be cool to merge quickly! Reason is we sent an email communication and are receiving support tickets about this topic, so I compiled the answers in the doc. Providing this FAQ should help decreasing their number.
=> NXDOC-2092: Add FAQ about MFA

src/studio/nuxeo-studio/studio-overview-and-concepts.md
Careful: I recommend not using this paragraph as a multiexcerpt for Web UI as you do today. Studio and Web UI can have different browser support patterns.
=> NXDOC-2096: better describe supported browsers for studio

src/studio/nuxeo-online-services-portal/security-improvements-faq.md
=> NXDOC-2101: reflect mfa go live

src/nxdoc/nuxeo-server/data-store/data-modeling/data-lists-and-directories.md, src/nxdoc/nuxeo-server/data-store/data-modeling/data-lists-and-directories/how-to-populate-a-directory-with-csv.md, src/nxdoc/nuxeo-server/rest-api/rest-api-endpoints/command-endpoint.md
The HOW-TO could be seen as a WIP, it remains too technical imho.
=> NXDOC-2071: Directory.LoadFromCSV documentation

src/client-apps/nuxeo-drive/nuxeo-drive-release-notes.md
=> Adjustments on Nuxeo Drive 4.4.2 release notes

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2020-04.md
Should go to prod April 13: wait before merge please!
=> NXDOC-2098: studio 3.29

src/nxdoc/getting-started/best-practices/nuxeo-platform-feature-table.md, src/nxdoc/getting-started/discover-nuxeo-platform-apis/setting-up-your-nuxeo-environment.md, src/nxdoc/nuxeo-add-ons.md, src/nxdoc/nuxeo-add-ons/installing-a-new-package-on-your-instance.md
Remove references to 'nuxeo-dam' package.
=> NXP-28626: make DAM part of the default distribution

src/nxdoc/nuxeo-server/rest-api/rest-api-endpoints/document-resources-endpoints.md
POST over /api/v1/id/{idOfTheDoc} creates a document by its parent id.
=> Update id Enpoint for POST

src/nxdoc/nuxeo-server/data-store/data-modeling/audit.md
10.10 API changes + Compilation fix
=> 10.10 API changes + Compilation fix

src/nxdoc/nuxeo-add-ons/nuxeo-jsf-ui/jsf-ui-framework/jsf-ui-how-to-index/how-to-bubble-errors-from-the-core-layer-in-the-jsf-ui.md
ClientException is deprecated.
=> Change ClientException into NuxeoException

src/nxdoc/nuxeo-server/authentication-and-user-management/using-oauth2.md
Properly document JWT token access with OAuth2
=> NXDOC-2060: Properly document JWT/OAuth2 bearer token acquision

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2020-05.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2020-06.md, src/studio/nuxeo-studio/working-in-view-designer/ui-designer.md
Already in prod, can be merged anytime.
=> NXDOC-2127: release notes for studio 3.30 / 3.31

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2020-06.md
To be merged May 29, prod deployment June 1 at 5 am paris.
=> NXDOC-2128: studio 3.31+

src/nxdoc/nuxeo-server/data-store/indexing-and-query/elasticsearch-hints-cheat-sheet.md
Following https://jira.nuxeo.com/browse/NXP-25315, add info on documentation page.
=> Add More Like This information

src/nxdoc/nuxeo-server/data-store/security/security-policy-service.md
It was only displayed on master
=> University Link Security Policy (1010)

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md
NOS team to schedule deployment for this release and inform you.
No particular impact (bugfix release), so no rush in merging this PR.
=> NXDOC-2135: studio 3.32 release notes

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-11-1-release-notes.md, src/nxdoc/web-ui/web-ui-roadmap.md, src/nxdoc/web-ui/web-ui-upgrade-notes.md, src/nxdoc/web-ui/web-ui-upgrade-notes/web-ui-11-1-upgrade-notes.md
To be reviewed by UI team first, then Manon for proofreading.
=> NXDOC-2138: web ui 11.1 release and upgrade notes

src/nxdoc/nuxeo-server/platform-services/comments.md
Details were requested concerning the auto subscription feature
=> NXDOC-2067: update the auto subscription documentation

src/client-apps/nuxeo-drive/nuxeo-drive-functional-overview.md
Manon, I just added the minimum details I need for the ticket. It may be enough until you will have time to expand a little more :)
=> NXDRIVE-2234: Add a simple Direct Transfer section

src/nxdoc/nuxeo-server/platform-services/automation/document-templates-and-automation-rendering-service.md
Cannot be backported on 10.10 (only available for 11.1)
=> NXDOC-2150: Allow Map and List in Nuxeo Platform Rendering templateParam

src/nxdoc/nuxeo-server/platform-services/automation/document-templates-and-automation-rendering-service.md
It should be replicated on the master branch once reviewed
=> NXDOC-2160: More info on Document rendering

src/nxdoc/web-ui/web-ui-tutorials/how-to-update-default-nuxeo-page.md
From https://nuxeo.slack.com/archives/C0FC1E6UD/p1595472844068700
=> Update way to override default contribs

src/nxdoc/nuxeo-server/nuxeo-server-roadmap.md
Would appreciate a merge asap, and relaunch a build (we're currently displaying internal info)
=> NXDOC-2162: fix roadmap displaying internal items

src/nxdoc/getting-started/best-practices/nuxeo-platform-feature-table.md
All changes made except the ones regarding liveconnect are relevant for backport to 10.10 doc
=> NXDOC-2167: update feature comparison table

src/nxdoc/nuxeo-server/upgrading-the-nuxeo-platform/upgrade-from-lts-2017-following-fast-tracks.md
Update the comment migration procedure adding the Detect button step.
=> Update the comment migration procedure

src/corg/coding-and-design-guidelines/code-review-guidelines.md
Note: the backport section has been removed and will be moved to the internal wiki.
=> NXDOC-2146: Complete and update Code Review Guidelines

src/studio/nuxeo-online-services-portal/account-management.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2020-07-08-09.md
Deployment scheduled on sep. 21
Please make sure to merge https://github.com/nuxeo/doc.nuxeo.com-content/pull/1553 before, this pr depends on it
=> NXDOC-2186: studio 3.34 release notes

src/nxdoc/nuxeo-server/administration/performances/tracking-the-performance-of-the-nuxeo-platform.md
Ideally this should also be merged on 10.10
=>  NXDOC-2197

src/client-apps/nuxeo-drive.md
Also removed the HTML table for titles and texts.
=> NXDRIVE-2318: Update Nuxeo Drive parameters

src/nxdoc/nuxeo-server/rest-api/rest-api-endpoints/batch-upload-endpoint.md, src/nxdoc/nuxeo-server/rest-api/rest-api-howtos/howto-upload-file-nuxeo-using-rest-api.md
To be merged after https://github.com/nuxeo/nuxeo/pull/4409.
Not to be backported on 10.10.
=> NXP-29796: change Batch Upload "resume incomplete" http code from 308 to 202

src/nxdoc/getting-started/tracks/develop-with-nuxeo-platform.md, src/nxdoc/nuxeo-add-ons/amazon-s3-online-storage.md, src/nxdoc/nuxeo-server/administration/implementing-encryption.md, src/nxdoc/nuxeo-server/administration/performances/tracking-the-performance-of-the-nuxeo-platform.md, src/nxdoc/nuxeo-server/installation.md, src/nxdoc/nuxeo-server/installation/compatibility-matrix.md, src/nxdoc/nuxeo-server/platform-services/automation/automation-scripting.md, src/nxdoc/nuxeo-server/runtime-and-component-model/runtime-and-component-model-tutorials/how-to-create-an-empty-bundle.md
Related to:
- https://github.com/nuxeo/jx-platform-builders/pull/41
- https://github.com/nuxeo/nuxeo/pull/4412
=> NXDOC-2218: Replace occurence of Oracle JDK by Azul Zulu OpenJDK

src/nxdoc/nuxeo-server/administration/elasticsearch-setup.md
Add information about explain and profile queries.
This can be applied on 1010 and the main branch.
=> ES explain and profile + format

src/nxdoc/web-ui/web-ui-tutorials/how-to-trigger-automation-dialog.md
- Can be copied to master once reviewed.
- Warning: I wasn't able to build the doc so sorry if the content is not properly formatted
=> NXDOC-2219: Trigger automation in a WebUI dialog

src/nxdoc/web-ui/web-ui-tutorials/how-to-update-default-nuxeo-page.md
=> Fix copy of default web ui elements

src/nxdoc/nuxeo-add-ons/nuxeo-retention-management.md
Add a warning and link to *configure-the-records-bucket-in-amazon-s3-online-storage*
* I think this can be applied as well the the NEXT version.
=> Warning and link to retention configure

src/nxdoc/nuxeo-server/platform-services/conversion.md
Update misleading comment for diskCacheSize
=> Update diskCacheSize misleading comment

assets/client-apps/nuxeo-drive-release-notes/DT-sessions-history.png, assets/client-apps/nuxeo-drive-release-notes/DT-sessions-monitoring.png, assets/client-apps/nuxeo-drive-release-notes/NXDRIVE-2359-after.png, assets/client-apps/nuxeo-drive-release-notes/NXDRIVE-2359-before.png, assets/client-apps/nuxeo-drive-release-notes/NXDRIVE-2359.png, src/client-apps/nuxeo-drive/nuxeo-drive-release-notes.md
Pictures were optimized using https://tinypng.com/.
=> NXDRIVE-2313: Adjust screenshots

src/nxdoc/web-ui/web-ui-tutorials/web-ui-routing.md
=> NXDOC-2201: Update Web UI routing documentation (2021)

src/nxdoc/nuxeo-add-ons/amazon-s3-online-storage.md
Can be backported to branch `2021`
=> NXP-29122: document new bucket permissions

src/nxdoc/web-ui/web-ui-tutorials/web-ui-routing.md
Backport of [#1646](https://github.com/nuxeo/doc.nuxeo.com-content/pull/1646).
=> NXDOC-2201: add example snippet to enable navigation by UID (2021)

src/nxdoc/web-ui/web-ui-upgrade-notes/web-ui-11-1-upgrade-notes.md
I've updated the Web UI upgrade notes, but I wonder if I should create a new file for it. Wdyt?
Reviews and feedback are very welcome :)
=> NXDOC-2221: update nuxeo-web-ui upgrade notes

src/nxdoc/web-ui/nuxeo-elements.md, src/nxdoc/web-ui/nuxeo-elements/nuxeo-elements-tutorial.md, src/nxdoc/web-ui/web-ui-overview.md
=> NXDOC-2226: remove node version in elements tutorial (2021)

src/nxdoc/web-ui/nuxeo-elements.md, src/nxdoc/web-ui/nuxeo-elements/nuxeo-elements-tutorial.md, src/nxdoc/web-ui/web-ui-overview.md
=> NXDOC-2226: remove node version in elements tutorial (1010)

src/nxdoc/web-ui/nuxeo-elements.md, src/nxdoc/web-ui/nuxeo-elements/nuxeo-elements-tutorial.md, src/nxdoc/web-ui/web-ui-overview.md
=> NXDOC-2226: add node version reference in elements tutorial (910)

src/nxdoc/nuxeo-server/administration/observability/metrics.md
Also, update the timer metrics filter
=> NXDOC-2277: Add missing configuration to activate metrics

src/nxdoc/getting-started/tracks/discover-nuxeo-platform-apis/setting-up-your-nuxeo-environment.md
- Remove references of MacOS or Windows installation (all in Docker)
- Add warning for the private image / sources
- Remove nuxeo-dam references as included by default
- Adapt Docker deployment for newbies, including tricks and tips
- Adapt the package version with the ZIP install 
To be replicated on master once reviewed and approved
=> NXDOC-2271 - Review Getting Started with LTS2021

src/client-apps/nuxeo-drive/nuxeo-drive-faq.md
Waiting on the beta 5.0.0 before merging.
=> NXDRIVE-2507: Update supported OSes

src/nxdoc/nuxeo-server/administration/configuration-parameters-index-nuxeoconf.md
=> Fix default client for Elasticsearch

src/client-apps/nuxeo-drive/nuxeo-drive-faq.md
Also sorted the array to list latest to older versions.
=> Update the Nuxeo Drive FAQ for the v5 version

src/nxdoc/web-ui/web-ui-tutorials/web-ui-slots.md
To be backported to master and 10.10
=> NXDOC-2293 - Add user attribute in the element details

src/nxdoc/nuxeo-server/installation/tomcat-server-zip/installing-and-setting-up-related-software.md
=> NXDOC-2299 - Update LibreOffice version for LTS2021

src/nxdoc/nuxeo-server/installation/docker-image.md
=> Explicit the docker image is using H2, ES and Chronical Queue

src/nxdoc/generic-multi-excerpts.md
=> Explicit the fact to create a support ticket to get access to the docker image

src/nxdoc/nuxeo-server/installation/nuxeo-and-redis.md
Add more context and details on redis administration for nuxeo.
Should be applied on all branchs.
=> Add more context and details on redis administration

src/nxdoc/nuxeo-server/platform-services/automation.md, src/nxdoc/web-ui/web-ui-tutorials/howto-execute-ui-functions.md
To be backported on master and LTS2019 🙏
=> University Course - Implement Business Logic (2021) - 2021

src/client-apps/nuxeo-drive.md, src/client-apps/nuxeo-drive/nuxeo-drive-metrics-documentation.md
Documentation for the Drive custom metrics
=> NXDRIVE-2561: Write the custom metrics documentation

src/nxdoc/nuxeo-server/administration/setup-best-practices.md
Following https://answers.nuxeo.com/general/q/ace9522a15d94d738ca22cce3a0f6344/Recommended-Xms-and-Xmx-values#a29b996e-350f-43b8-9341-cf0a4dd3ef74 feedback
=> Update setup best practices for LTS2019

src/nxdoc/nuxeo-server/administration/monitoring-and-maintenance/hotfixes-installation-notes-for-nuxeo-platform-lts-2019.md
Add precision when configuring the StreamWorkManager filter.
=> configure StreamWorkManager filter

src/client-apps/nuxeo-drive.md
Please do not merge until the release, I'll ping again when necessary :)
=> NXDRIVE-2654: exec-profile has been removed

src/nxdoc/nuxeo-server/authentication-and-user-management/authentication-and-user-management-tutorials/how-to-add-new-fields-to-the-user-profile-or-group-profile.md
On master branch too once reviewed
=> NXDOC-2341 - Custom user fields OK for LTS2021 and Web UI 3.0.3

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2021-06.md
=> final 4.5 release

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2021-07.md
Accessibility improvements for Studio 4.5.x
=> NXDOC-2353 studio designer 4.5.x

src/nxdoc/web-ui/web-ui-tutorials/how-to-create-bulk-actions-studio.md, src/nxdoc/web-ui/web-ui-tutorials/how-to-insert-user-action.md, src/nxdoc/web-ui/web-ui-tutorials/how-to-use-events.md, src/nxdoc/web-ui/web-ui-tutorials/web-ui-bulk-actions.md, src/userdoc/web-ui/managing-content/content-delete.md, src/userdoc/web-ui/organizing-content/collections-web-ui.md
Missing images but should be enough to do a first round of review.
Configuration in Studio will be sent in a separate PR as it impacts another branch.
=> NXDOC-2333: document Web UI bulk actions

src/studio/nuxeo-studio/administering-your-project/project-inheritance-multi-layer.md
=> NXDOC-2328:  multilayer changes

src/nxdoc/nuxeo-add-ons/nuxeo-frameio.md
Fixed up a bunch of copy and clarified a few things.
=> Improved copy

src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-10-6-10.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-10-6-7.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-10-6-8.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-10-6-9.md
Can you please apply to LTS 2019 too ?
=> NXDOC-2397 initial commit

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-7.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-8.md
Release to be generally available on Nov. 29
=> NXDOC-2398: release notes for Web UI 3.0.8

src/nxdoc/nuxeo-add-ons/nuxeo-retention-management.md, src/nxdoc/nuxeo-add-ons/nuxeo-retention-management/nuxeo-retention-functional-overview.md, src/nxdoc/nuxeo-add-ons/nuxeo-retention-management/nuxeo-retention-installation.md
Please add it to both LTS 2021 and LTS 2019
=> NXDOC-2385 initial commit + add delete capability details

src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-0-0.md
Can you please backport to 10.10
=> NXDOC-2413 RN for 2.0.0 initial commit

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2021-09.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2021-11.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2021-12.md
Changes for Nov and Dec, unhide Sept
=> Changes for Nov and Dec, unhide Sept

src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer.md
To be reviewed and backport to 2019 once ready please
=> NXDOC-2414 initial commit

src/nxdoc/web-ui/web-ui-upgrade-notes/web-ui-upgrade-notes-lts-2021.md
=> NXDOC-2402: reference routing changes in upgrade notes (2021)

src/nxdoc/nuxeo-server/platform-services/file-manager.md
- Missing code
- link to tutorial
=> Improvements requested by customer

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-10.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-11.md, src/nxdoc/web-ui/web-ui-tutorials/how-to-create-bulk-edit-form-studio.md, src/nxdoc/web-ui/web-ui-tutorials/web-ui-bulk-actions.md
General availability on Apr. 4 
=> merge on Apr. 1 (sooner is ok)
=> remember to backport to LTS 2021 ;-)
=> NXDOC-2444: web ui 3.0.11 release notes and matching updates

assets/nxdoc/master/web-ui-overview/2021-10-Nuxeo-Web-UI-LTS-2021-3-0-6-VPAT.pdf, assets/nxdoc/master/web-ui-overview/2022-04-nuxeo-web-ui-lts-2021-3-0-11-vpat.pdf, src/nxdoc/web-ui/web-ui-overview.md
can be merged as soon as you're ready
=> NXDOC-2445: VPAT for Web UI 3.0.11

src/studio/nuxeo-studio/nuxeo-studio-release-notes.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2021-12.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2022-02.md, src/studio/nuxeo-studio/nuxeo-studio-release-notes/studio-updates-2022-03.md
=> Nos release 4.10 et 2022.1

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-11.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-12.md
To be merged on May 13 (friday) or sooner if needed
Release GA on May 16 (following monday)
=> NXDOC-2457: web ui 3.0.12 release notes

src/nxdoc/nuxeo-server/data-store/indexing-and-query/nxql.md
provides a better explanation on how to draw the square with the coordinates where to search the documents
=> NXDOC-2464: geo_bounding_box operator update

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-12.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-13.md
Please merge on June 24 (or sooner)
Release GA on June 27
PR can be merged as is, if ELEMENTS-1490 gets merged in the meantime I'll update the PR to reflect it.
=> NXDOC-2465: Release notes for Web UI 3.0.13

src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-10-6-11.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-1-0.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-1-2.md
To be merged as soon as release can be done :)
=> NXDOC-2469: Release notes for NEV 2.1.2

src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/how-to-import-documents-with-annotations.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/how-to-use-content-redaction.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-10-6-11.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-0-0.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-1-0.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-1-2.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-2-0.md, src/nxdoc/nuxeo-server/nuxeo-data-privacy.md
Currently waiting for https://jira.nuxeo.com/browse/NXDOC-2454 and https://jira.nuxeo.com/browse/NXDOC-2481 from @kevinleturc 
Could not test the PR locally due to a build issue
=> NXDOC-2455: NEV - Content redaction

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-13.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-14.md
Release is GA on monday, aug. 8
=> NXDOC-2483: web ui 3.0.14 release notes

src/userdoc/adding-features/nuxeo-imap-connector.md
https://jira.nuxeo.com/browse/NXDOC-2476
=> Imp nxdoc 2476 imap connector

src/nxdoc/web-ui/polymer-guide.md
Draft for https://jira.nuxeo.com/browse/NXDOC-2490
@mgavanon will follow up on it before this gets merged.
=> NXDOC-2490: draft polymer and future of web ui

assets/nxdoc/web-ui-slots/PUBLISH_PAGES.png, assets/nxdoc/web-ui-slots/TRASH_RESULTS_SELECTION_ACTIONS.png, src/nxdoc/web-ui/web-ui-tutorials/web-ui-slots.md
Hi @bchauvin ,
cc: @manonlumeau
As we discussed I am going to open a PR for review and modification and it needs some changes with the label and description as well, Kindly have a look and suggested to me further changes in those new slots.
=> NXDOC-2498: added new documentation missing slots

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-16.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-17.md
GA on monday, dec. 12
=> to publish and backport to LTS 2021 asap please :pray:
=> NXDOC-2517: web ui 3.0.17 release notes

src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-1-2.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-1-3.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-1-4.md
Releases are available.
2.1.4 fixes a security issue and communication is about to be sent, so I believe we should merge on monday if possible.
=> NXDOC-2518: NEV 2.1.3 and 2.1.4

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-17.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-18.md
Can be merged anytime, release is already available publicly.
Needs to be backported to LTS 2021.
=> NXDOC-2529: Web UI 3.0.18 release notes

src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-0-0.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-1-0.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-1-2.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-1-3.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-1-4.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-2-0.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-2-1.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-3-0.md
@bchauvin there's several thing to change / update / add. I just added the breaking change introduced in this version.
=> Document breaking change for NEV 2.3.0

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-19.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-20.md, src/nxdoc/web-ui/web-ui-upgrade-notes.md
Generally available on March 6.
PR needs to be backported to LTS 2021 branch.
=> NXDOC-2544: Release notes for web ui 3.0.20

src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-3-0.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2-3-1.md
[NXDOC-2556](https://jira.nuxeo.com/browse/NXDOC-2556): NEV 2.3.1 release notes
Already available, can be merged asap
=> NXDOC-2556: release notes for NEV 2.3.1

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-21.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-22.md
The release is generally available on May 10.
https://jira.nuxeo.com/browse/NXDOC-2562
=> NXDOC-2562: Release notes for web ui 3.0.22

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-22.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-23.md
This release will be available on 30th May.
=> NXDOC-2566: Release notes for web ui 3.0.23

src/nxdoc/nuxeo-server/administration/maintenance/garbage-collecting-orphaned-binaries.md, src/nxdoc/nuxeo-server/administration/maintenance/garbage-collecting-orphaned-blobs.md, src/nxdoc/nuxeo-server/rest-api/rest-api-endpoints.md
See also https://github.com/nuxeo/doc.nuxeo.com-rest-api/pull/54
=> Task nxdoc 2561 new full gc 2021

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-23.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-24.md
This release will be available on 21st June.
=> NXDOC-2570: Release notes for web ui 3.0.24

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-24.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-25.md
This release will be available on the 17th of July.
=> NXDOC-2576: Release notes for web ui 3.0.25

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-2.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-3.md
=> NXDOC-2587: release notes for web ui 3.1.3

src/javadoc/2019-lts.md, src/javadoc/2021-lts.md, src/javadoc/2023-lts.md
This PR needs the following PR to work as expected:
- https://github.com/nuxeo/doc.nuxeo.com/pull/120
=> NXBT-3743: Link the new Nuxeo LTS javadoc

src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-3.md
=> NXDOC-2592: fix mention of LTS 2021

src/nxdoc/nuxeo-add-ons/nuxeo-retention-management.md, src/nxdoc/nuxeo-add-ons/nuxeo-retention-management/nuxeo-retention-functional-overview.md, src/nxdoc/nuxeo-add-ons/nuxeo-retention-management/nuxeo-retention-howto-undeclare-records.md, src/nxdoc/nuxeo-add-ons/nuxeo-retention-management/nuxeo-retention-installation.md, src/nxdoc/nuxeo-add-ons/nuxeo-retention-management/nuxeo-retention-installation/nuxeo-retention-installation-standard.md, src/nxdoc/nuxeo-add-ons/nuxeo-retention-management/nuxeo-retention-installation/nuxeo-retention-installation-strict.md
Release to be made GA at latest on Sep. 28
=> NXDOC-2595: flexible retention functional update

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-27.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-28.md
The WebUI release generally will be available on the 4th of October
=> NXDOC-2604: release notes for web ui 3.0.28

src/nxdoc/nuxeo-server/installation/docker-image.md
Also, update Rocky Linux base image version.
=> NXP-31815: Document Docker image architecture variants, amd64 and arm64

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-28.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-29.md
This release will be available on the 6th of December.
=> NXDOC-2622: release notes for web ui 3.0.29

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-3.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-4.md
This release was done on the 1st of December.
=> NXDOC-2624: release notes for web ui 3.1.4

assets/nxdoc/web-ui-accessibility/2023-07-nuxeo-web-ui-3-1-2-vpat.pdf, assets/nxdoc/web-ui-accessibility/2023-12-nuxeo-web-ui-3-1-4-vpat.pdf, src/nxdoc/web-ui/web-ui-accessibility.md
=> NXDOC-2625: Update VPAT for Web UI 3.1.4

assets/nxdoc/2021/web-ui-accessibility/2023-05-nuxeo-web-ui-3-0-22-vpat.pdf, assets/nxdoc/web-ui-accessibility/2023-12-nuxeo-web-ui-3-0-29-vpat.pdf, src/nxdoc/web-ui/web-ui-accessibility.md
=> NXDOC-2623: update VPAT for web ui 3.0.29

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-upgrade-notes.md, src/nxdoc/web-ui/web-ui-upgrade-notes/web-ui-upgrade-notes-lts-2023.md
Can be merged asap, necessary to inform customers about the change.
=> NXDOC-2638: nodejs 18 upgrade notice

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-upgrade-notes.md, src/nxdoc/web-ui/web-ui-upgrade-notes/web-ui-upgrade-notes-lts-2021.md
=> NXDOC-2638: nodejs 18 upgrade notice 2021

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-29.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-30.md
This release will be publicly available on 5th Feb.
=> NXDOC-2641: release notes for web ui 3.0.30

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-4.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-5.md
This release will be publicly available on 5th Feb.
=> NXDOC-2640: release notes for web ui 3.1.5

src/nxdoc/nuxeo-add-ons/nuxeo-retention-management/nuxeo-retention-functional-overview.md, src/nxdoc/nuxeo-add-ons/nuxeo-retention-management/nuxeo-retention-howto-retain-multiple-blobs.md, src/nxdoc/nuxeo-add-ons/nuxeo-retention-management/nuxeo-retention-howto-undeclare-records.md
=> NXDOC-2532: howto retain multiple blobs

src/nxdoc/nuxeo-add-ons/nuxeo-retention-management/nuxeo-retention-functional-overview.md, src/nxdoc/nuxeo-add-ons/nuxeo-retention-management/nuxeo-retention-howto-undeclare-records.md
Currently missing the icon to undeclare a record as I do not have access to the intranet.
=> NXDOC-2636: mention UI options for flexible retention

src/nxdoc/nuxeo-add-ons/nuxeo-retention-management/nuxeo-retention-functional-overview.md, src/nxdoc/nuxeo-add-ons/nuxeo-retention-management/nuxeo-retention-howto-undeclare-records.md
Same PR as the one for LTS 2023, missing the icon for now.
=> NXDOC-2636: backport to LTS 2021

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-5.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-6.md
https://jira.nuxeo.com/browse/NXDOC-2654
=> NXDOC-2654: release notes for web ui 3.1.6

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-6.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-7.md
General availability on March 26.
@MateuszTomaska please ensure that the PR is merged by this date.
=> NXDOC-2657: release notes for Web UI 3.1.7

src/nxdoc/nuxeo-add-ons.md, src/nxdoc/nuxeo-add-ons/nuxeo-keycloak.md
=> task-NXDOC-2663-Document-the-nuxeo-keycloak-package

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-8.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-9.md
https://jira.nuxeo.com/browse/NXDOC-2672
=> NXDOC-2672: release notes for WEBUI 3.1.9

src/nuxeo-cloud/index.md, src/nuxeo-cloudindex.md
Remove redundant link to the "Start Developing an Application" page.
=> Remove redundant link from the index.md file

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-34.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-35.md
https://jira.nuxeo.com/browse/NXDOC-2707
=> NXDOC-2707: release notes for 3.0.35

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-10.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-11.md
https://jira.nuxeo.com/browse/NXDOC-2707
=> NXDOC-2707: release notes for 3.1.11

src/nxdoc/nuxeo-server/administration/configuration-parameters-index-nuxeoconf.md
https://jira.nuxeo.com/browse/NXDOC-2708
=> NXDOC-2708: update nuxeo document for adding new property in nuxeo conf file

src/nxdoc/nuxeo-server/administration/configuration-parameters-index-nuxeoconf.md
=> NXDOC-2715: update nuxeo document for adding new property trusted domian in nuxeo conf file - 2021

src/nxdoc/nuxeo-server/administration/configuration-parameters-index-nuxeoconf.md
=> NXDOC-2715: update nuxeo document for adding new property trusted domian in nuxeo conf file - 2023

assets/nxdoc/web-ui-accessibility/2023-12-nuxeo-web-ui-3-1-4-vpat.pdf, assets/nxdoc/web-ui-accessibility/2024-09-nuxeo-web-ui-3-1-12-vpat.pdf, src/nxdoc/web-ui/web-ui-accessibility.md
=> NXDOC-2724: web ui vpat update

assets/nxdoc/web-ui-accessibility/2023-12-nuxeo-web-ui-3-0-29-vpat.pdf, assets/nxdoc/web-ui-accessibility/2024-09-nuxeo-web-ui-3-0-36-vpat.pdf, src/nxdoc/web-ui/web-ui-accessibility.md
=> NXDOC-2725: web ui vpat update

src/nxdoc/nuxeo-server/platform-services/automation/automation-how-to-index/howto-manage-relations.md
Change folder name from **Relations** to **relations** in the How to manage relations page wherever applicable.
=> NXDOC-2734 Update folder name in howto-manage-relations.md for 2021 LTS

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-36.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-37.md
https://jira.nuxeo.com/browse/NXDOC-2732
=> NXDOC-2732: Release notes for WEB UI 3.0.37

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-12.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-13.md
https://jira.nuxeo.com/browse/NXDOC-2732
=> NXDOC-2732: Release notes for WEB UI 3.1.13

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-38.md
https://hyland.atlassian.net/browse/NXDOC-2743
=> NXDOC-2743: Release notes for WEB UI 3.0.38

src/nxdoc/nuxeo-server/administration/configuration-parameters-index-nuxeoconf.md
https://hyland.atlassian.net/browse/NXDOC-2747
=> NXDOC-2747:update nuxeo document for adding new property in nuxeo conf file

src/nxdoc/nuxeo-server/administration/configuration-parameters-index-nuxeoconf.md
https://hyland.atlassian.net/browse/NXDOC-2747
=> NXDOC-2747:update nuxeo document for adding new property in nuxeo conf file 2021

src/nxdoc/nuxeo-server/administration/configuration-parameters-index-nuxeoconf.md
=> NXDOC-2753: Allow to configure the Content Security Policy with nuxeo conf parameter for WEB UI  2021

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-14.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-15.md
https://hyland.atlassian.net/browse/NXDOC-2748
=> NXDOC-2748: Release notes for WEB UI 3.1.15

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-38.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-39.md
https://hyland.atlassian.net/browse/NXDOC-2748
=> NXDOC-2748: Release notes for WEB UI 3.0.39

src/nxdoc/nuxeo-add-ons/nuxeo-compound-documents.md
added markdown ticks for the code block for some of the scripting information.
=> NXDOC-2763 Update nuxeo-compound-documents.md

src/nxdoc/nuxeo-server/administration/configuration-parameters-index-nuxeoconf.md
Task nxdoc 2764 update nuxeo document for adding new property eval in nuxeo conf file 2023
=> NXDOC-2764: update nuxeo document for adding new property eval in nuxeo conf file 2023

src/nxdoc/nuxeo-server/administration/configuration-parameters-index-nuxeoconf.md
NXDOC-2764: update nuxeo document for adding new property eval in nuxeo conf file
=> NXDOC-2764: update nuxeo document for adding new property eval in nuxeo conf file

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-39.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-40.md
https://hyland.atlassian.net/browse/NXDOC-2761
=> NXDOC-2761: Release notes for WEB UI 3.0.40

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-16.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-17.md
https://hyland.atlassian.net/browse/NXDOC-2778
=> NXDOC-2778:  Release notes for WEB UI 3.1.17

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-17.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-18.md
https://hyland.atlassian.net/browse/NXDOC-2796
=> NXDOC-2796: WEBUI 3.1.18 release notes

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-41.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-0-42.md
https://hyland.atlassian.net/browse/NXDOC-2796
=> NXDOC-2796: WEBUI 3.0.42 release notes

src/nxdoc/nuxeo-add-ons/nuxeo-connector-content-intelligence.md
Included the Connector download link.
=> NXDOC-2795 Update nuxeo-connector-content-intelligence.md

src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-installation.md, src/nxdoc/nuxeo-add-ons/nuxeo-enhanced-viewer/nuxeo-enhanced-viewer-release-notes/nuxeo-enhanced-viewer-release-notes-2025-0-0.md
This is a small updates reflecting recent 2025.0.0 major release.
=> Update the NEV version to latest major

src/nxdoc/nuxeo-server/installation/docker-image/build-a-custom-docker-image.md
This reverts commit 21c1d2b45a7c0e2c5d87346245f95568653166a5.
=> Revert "NXP-33075: Temporarily remove FFMpeg section" (2025)

src/nxdoc/nuxeo-add-ons/nuxeo-ai/nuxeo-ai-release-notes/nuxeo-ai-4.0.2.md
Added release notes for nuxeo-ai-4.0.2
=> Nuxeo AI 4.0.2 upgrade release notes

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-2025-5-0.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-2025-6-0.md
https://hyland.atlassian.net/browse/NXDOC-2835
=> NXDOC-2835 WEBUI-2025.6.0

src/nxdoc/nuxeo-add-ons/nuxeo-aspera-connector/nuxeo-aspera-upgrade-notes.md
Reverts nuxeo/doc.nuxeo.com-content#2503
=> Revert "NXDOC-2839 Fix JIRA URLs in Nuxeo Aspera Release Notes documentation"

src/nxdoc/nuxeo-server/administration/search-setup.md
Reverts nuxeo/doc.nuxeo.com-content#2509
=> Revert "NXDOC-2842: Warn on es multi repo conf"

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-2025-6-0.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-2025-7-0.md
https://hyland.atlassian.net/browse/NXDOC-2847
=> NXDOC-2847: WEBUI Release Notes 2025.7.0

src/nxdoc/web-ui/web-ui-release-notes.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-21.md, src/nxdoc/web-ui/web-ui-release-notes/web-ui-release-notes-3-1-22.md
https://hyland.atlassian.net/browse/NXDOC-2848
=> NXDOC-2848: WEBUI Release Notes 3.1.22
